// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017 The go-ovh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/appscode/go-ovh/me/models"
)

// GetMeSSHKeyKeyNameReader is a Reader for the GetMeSSHKeyKeyName structure.
type GetMeSSHKeyKeyNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMeSSHKeyKeyNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetMeSSHKeyKeyNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetMeSSHKeyKeyNameDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetMeSSHKeyKeyNameOK creates a GetMeSSHKeyKeyNameOK with default headers values
func NewGetMeSSHKeyKeyNameOK() *GetMeSSHKeyKeyNameOK {
	return &GetMeSSHKeyKeyNameOK{}
}

/*GetMeSSHKeyKeyNameOK handles this case with default header values.

description of 'nichandle.SshKey' response
*/
type GetMeSSHKeyKeyNameOK struct {
	Payload *models.NichandleSSHKey
}

func (o *GetMeSSHKeyKeyNameOK) Error() string {
	return fmt.Sprintf("[GET /me/sshKey/{keyName}][%d] getMeSshKeyKeyNameOK  %+v", 200, o.Payload)
}

func (o *GetMeSSHKeyKeyNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NichandleSSHKey)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetMeSSHKeyKeyNameDefault creates a GetMeSSHKeyKeyNameDefault with default headers values
func NewGetMeSSHKeyKeyNameDefault(code int) *GetMeSSHKeyKeyNameDefault {
	return &GetMeSSHKeyKeyNameDefault{
		_statusCode: code,
	}
}

/*GetMeSSHKeyKeyNameDefault handles this case with default header values.

Unexpected error
*/
type GetMeSSHKeyKeyNameDefault struct {
	_statusCode int

	Payload *models.GetMeSSHKeyKeyNameDefaultBody
}

// Code gets the status code for the get me SSH key key name default response
func (o *GetMeSSHKeyKeyNameDefault) Code() int {
	return o._statusCode
}

func (o *GetMeSSHKeyKeyNameDefault) Error() string {
	return fmt.Sprintf("[GET /me/sshKey/{keyName}][%d] GetMeSSHKeyKeyName default  %+v", o._statusCode, o.Payload)
}

func (o *GetMeSSHKeyKeyNameDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetMeSSHKeyKeyNameDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
