// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017 The go-ovh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/appscode/go-ovh/me/models"
)

// GetMePaymentMeanCreditCardReader is a Reader for the GetMePaymentMeanCreditCard structure.
type GetMePaymentMeanCreditCardReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMePaymentMeanCreditCardReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetMePaymentMeanCreditCardOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetMePaymentMeanCreditCardDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetMePaymentMeanCreditCardOK creates a GetMePaymentMeanCreditCardOK with default headers values
func NewGetMePaymentMeanCreditCardOK() *GetMePaymentMeanCreditCardOK {
	return &GetMePaymentMeanCreditCardOK{}
}

/*GetMePaymentMeanCreditCardOK handles this case with default header values.

return value
*/
type GetMePaymentMeanCreditCardOK struct {
	Payload []int64
}

func (o *GetMePaymentMeanCreditCardOK) Error() string {
	return fmt.Sprintf("[GET /me/paymentMean/creditCard][%d] getMePaymentMeanCreditCardOK  %+v", 200, o.Payload)
}

func (o *GetMePaymentMeanCreditCardOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetMePaymentMeanCreditCardDefault creates a GetMePaymentMeanCreditCardDefault with default headers values
func NewGetMePaymentMeanCreditCardDefault(code int) *GetMePaymentMeanCreditCardDefault {
	return &GetMePaymentMeanCreditCardDefault{
		_statusCode: code,
	}
}

/*GetMePaymentMeanCreditCardDefault handles this case with default header values.

Unexpected error
*/
type GetMePaymentMeanCreditCardDefault struct {
	_statusCode int

	Payload *models.GetMePaymentMeanCreditCardDefaultBody
}

// Code gets the status code for the get me payment mean credit card default response
func (o *GetMePaymentMeanCreditCardDefault) Code() int {
	return o._statusCode
}

func (o *GetMePaymentMeanCreditCardDefault) Error() string {
	return fmt.Sprintf("[GET /me/paymentMean/creditCard][%d] GetMePaymentMeanCreditCard default  %+v", o._statusCode, o.Payload)
}

func (o *GetMePaymentMeanCreditCardDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetMePaymentMeanCreditCardDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
