// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017 The go-ovh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/appscode/go-ovh/me/models"
)

// GetMeBillBillIDDebtReader is a Reader for the GetMeBillBillIDDebt structure.
type GetMeBillBillIDDebtReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMeBillBillIDDebtReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetMeBillBillIDDebtOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetMeBillBillIDDebtDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetMeBillBillIDDebtOK creates a GetMeBillBillIDDebtOK with default headers values
func NewGetMeBillBillIDDebtOK() *GetMeBillBillIDDebtOK {
	return &GetMeBillBillIDDebtOK{}
}

/*GetMeBillBillIDDebtOK handles this case with default header values.

description of 'debt.Debt' response
*/
type GetMeBillBillIDDebtOK struct {
	Payload *models.DebtDebt
}

func (o *GetMeBillBillIDDebtOK) Error() string {
	return fmt.Sprintf("[GET /me/bill/{billId}/debt][%d] getMeBillBillIdDebtOK  %+v", 200, o.Payload)
}

func (o *GetMeBillBillIDDebtOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DebtDebt)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetMeBillBillIDDebtDefault creates a GetMeBillBillIDDebtDefault with default headers values
func NewGetMeBillBillIDDebtDefault(code int) *GetMeBillBillIDDebtDefault {
	return &GetMeBillBillIDDebtDefault{
		_statusCode: code,
	}
}

/*GetMeBillBillIDDebtDefault handles this case with default header values.

Unexpected error
*/
type GetMeBillBillIDDebtDefault struct {
	_statusCode int

	Payload *models.GetMeBillBillIDDebtDefaultBody
}

// Code gets the status code for the get me bill bill ID debt default response
func (o *GetMeBillBillIDDebtDefault) Code() int {
	return o._statusCode
}

func (o *GetMeBillBillIDDebtDefault) Error() string {
	return fmt.Sprintf("[GET /me/bill/{billId}/debt][%d] GetMeBillBillIDDebt default  %+v", o._statusCode, o.Payload)
}

func (o *GetMeBillBillIDDebtDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetMeBillBillIDDebtDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
