// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017 The go-ovh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/appscode/go-ovh/me/models"
)

// GetMeAccessRestrictionTotpReader is a Reader for the GetMeAccessRestrictionTotp structure.
type GetMeAccessRestrictionTotpReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMeAccessRestrictionTotpReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetMeAccessRestrictionTotpOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetMeAccessRestrictionTotpDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetMeAccessRestrictionTotpOK creates a GetMeAccessRestrictionTotpOK with default headers values
func NewGetMeAccessRestrictionTotpOK() *GetMeAccessRestrictionTotpOK {
	return &GetMeAccessRestrictionTotpOK{}
}

/*GetMeAccessRestrictionTotpOK handles this case with default header values.

return value
*/
type GetMeAccessRestrictionTotpOK struct {
	Payload []int64
}

func (o *GetMeAccessRestrictionTotpOK) Error() string {
	return fmt.Sprintf("[GET /me/accessRestriction/totp][%d] getMeAccessRestrictionTotpOK  %+v", 200, o.Payload)
}

func (o *GetMeAccessRestrictionTotpOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetMeAccessRestrictionTotpDefault creates a GetMeAccessRestrictionTotpDefault with default headers values
func NewGetMeAccessRestrictionTotpDefault(code int) *GetMeAccessRestrictionTotpDefault {
	return &GetMeAccessRestrictionTotpDefault{
		_statusCode: code,
	}
}

/*GetMeAccessRestrictionTotpDefault handles this case with default header values.

Unexpected error
*/
type GetMeAccessRestrictionTotpDefault struct {
	_statusCode int

	Payload *models.GetMeAccessRestrictionTotpDefaultBody
}

// Code gets the status code for the get me access restriction totp default response
func (o *GetMeAccessRestrictionTotpDefault) Code() int {
	return o._statusCode
}

func (o *GetMeAccessRestrictionTotpDefault) Error() string {
	return fmt.Sprintf("[GET /me/accessRestriction/totp][%d] GetMeAccessRestrictionTotp default  %+v", o._statusCode, o.Payload)
}

func (o *GetMeAccessRestrictionTotpDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetMeAccessRestrictionTotpDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
