// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017 The go-ovh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetMeDepositDepositIDPaymentParams creates a new GetMeDepositDepositIDPaymentParams object
// with the default values initialized.
func NewGetMeDepositDepositIDPaymentParams() *GetMeDepositDepositIDPaymentParams {
	var ()
	return &GetMeDepositDepositIDPaymentParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetMeDepositDepositIDPaymentParamsWithTimeout creates a new GetMeDepositDepositIDPaymentParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetMeDepositDepositIDPaymentParamsWithTimeout(timeout time.Duration) *GetMeDepositDepositIDPaymentParams {
	var ()
	return &GetMeDepositDepositIDPaymentParams{

		timeout: timeout,
	}
}

// NewGetMeDepositDepositIDPaymentParamsWithContext creates a new GetMeDepositDepositIDPaymentParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetMeDepositDepositIDPaymentParamsWithContext(ctx context.Context) *GetMeDepositDepositIDPaymentParams {
	var ()
	return &GetMeDepositDepositIDPaymentParams{

		Context: ctx,
	}
}

// NewGetMeDepositDepositIDPaymentParamsWithHTTPClient creates a new GetMeDepositDepositIDPaymentParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetMeDepositDepositIDPaymentParamsWithHTTPClient(client *http.Client) *GetMeDepositDepositIDPaymentParams {
	var ()
	return &GetMeDepositDepositIDPaymentParams{
		HTTPClient: client,
	}
}

/*GetMeDepositDepositIDPaymentParams contains all the parameters to send to the API endpoint
for the get me deposit deposit ID payment operation typically these are written to a http.Request
*/
type GetMeDepositDepositIDPaymentParams struct {

	/*DepositID*/
	DepositID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get me deposit deposit ID payment params
func (o *GetMeDepositDepositIDPaymentParams) WithTimeout(timeout time.Duration) *GetMeDepositDepositIDPaymentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get me deposit deposit ID payment params
func (o *GetMeDepositDepositIDPaymentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get me deposit deposit ID payment params
func (o *GetMeDepositDepositIDPaymentParams) WithContext(ctx context.Context) *GetMeDepositDepositIDPaymentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get me deposit deposit ID payment params
func (o *GetMeDepositDepositIDPaymentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get me deposit deposit ID payment params
func (o *GetMeDepositDepositIDPaymentParams) WithHTTPClient(client *http.Client) *GetMeDepositDepositIDPaymentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get me deposit deposit ID payment params
func (o *GetMeDepositDepositIDPaymentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDepositID adds the depositID to the get me deposit deposit ID payment params
func (o *GetMeDepositDepositIDPaymentParams) WithDepositID(depositID string) *GetMeDepositDepositIDPaymentParams {
	o.SetDepositID(depositID)
	return o
}

// SetDepositID adds the depositId to the get me deposit deposit ID payment params
func (o *GetMeDepositDepositIDPaymentParams) SetDepositID(depositID string) {
	o.DepositID = depositID
}

// WriteToRequest writes these params to a swagger request
func (o *GetMeDepositDepositIDPaymentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param depositId
	if err := r.SetPathParam("depositId", o.DepositID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
