// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017 The go-ovh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetMeAccessRestrictionU2fIDParams creates a new GetMeAccessRestrictionU2fIDParams object
// with the default values initialized.
func NewGetMeAccessRestrictionU2fIDParams() *GetMeAccessRestrictionU2fIDParams {
	var ()
	return &GetMeAccessRestrictionU2fIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetMeAccessRestrictionU2fIDParamsWithTimeout creates a new GetMeAccessRestrictionU2fIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetMeAccessRestrictionU2fIDParamsWithTimeout(timeout time.Duration) *GetMeAccessRestrictionU2fIDParams {
	var ()
	return &GetMeAccessRestrictionU2fIDParams{

		timeout: timeout,
	}
}

// NewGetMeAccessRestrictionU2fIDParamsWithContext creates a new GetMeAccessRestrictionU2fIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetMeAccessRestrictionU2fIDParamsWithContext(ctx context.Context) *GetMeAccessRestrictionU2fIDParams {
	var ()
	return &GetMeAccessRestrictionU2fIDParams{

		Context: ctx,
	}
}

// NewGetMeAccessRestrictionU2fIDParamsWithHTTPClient creates a new GetMeAccessRestrictionU2fIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetMeAccessRestrictionU2fIDParamsWithHTTPClient(client *http.Client) *GetMeAccessRestrictionU2fIDParams {
	var ()
	return &GetMeAccessRestrictionU2fIDParams{
		HTTPClient: client,
	}
}

/*GetMeAccessRestrictionU2fIDParams contains all the parameters to send to the API endpoint
for the get me access restriction u2f ID operation typically these are written to a http.Request
*/
type GetMeAccessRestrictionU2fIDParams struct {

	/*ID*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get me access restriction u2f ID params
func (o *GetMeAccessRestrictionU2fIDParams) WithTimeout(timeout time.Duration) *GetMeAccessRestrictionU2fIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get me access restriction u2f ID params
func (o *GetMeAccessRestrictionU2fIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get me access restriction u2f ID params
func (o *GetMeAccessRestrictionU2fIDParams) WithContext(ctx context.Context) *GetMeAccessRestrictionU2fIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get me access restriction u2f ID params
func (o *GetMeAccessRestrictionU2fIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get me access restriction u2f ID params
func (o *GetMeAccessRestrictionU2fIDParams) WithHTTPClient(client *http.Client) *GetMeAccessRestrictionU2fIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get me access restriction u2f ID params
func (o *GetMeAccessRestrictionU2fIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get me access restriction u2f ID params
func (o *GetMeAccessRestrictionU2fIDParams) WithID(id int64) *GetMeAccessRestrictionU2fIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get me access restriction u2f ID params
func (o *GetMeAccessRestrictionU2fIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetMeAccessRestrictionU2fIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
