// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017 The go-ovh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/appscode/go-ovh/me/models"
)

// NewPutMeAccessRestrictionU2fIDParams creates a new PutMeAccessRestrictionU2fIDParams object
// with the default values initialized.
func NewPutMeAccessRestrictionU2fIDParams() *PutMeAccessRestrictionU2fIDParams {
	var ()
	return &PutMeAccessRestrictionU2fIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutMeAccessRestrictionU2fIDParamsWithTimeout creates a new PutMeAccessRestrictionU2fIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutMeAccessRestrictionU2fIDParamsWithTimeout(timeout time.Duration) *PutMeAccessRestrictionU2fIDParams {
	var ()
	return &PutMeAccessRestrictionU2fIDParams{

		timeout: timeout,
	}
}

// NewPutMeAccessRestrictionU2fIDParamsWithContext creates a new PutMeAccessRestrictionU2fIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutMeAccessRestrictionU2fIDParamsWithContext(ctx context.Context) *PutMeAccessRestrictionU2fIDParams {
	var ()
	return &PutMeAccessRestrictionU2fIDParams{

		Context: ctx,
	}
}

// NewPutMeAccessRestrictionU2fIDParamsWithHTTPClient creates a new PutMeAccessRestrictionU2fIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutMeAccessRestrictionU2fIDParamsWithHTTPClient(client *http.Client) *PutMeAccessRestrictionU2fIDParams {
	var ()
	return &PutMeAccessRestrictionU2fIDParams{
		HTTPClient: client,
	}
}

/*PutMeAccessRestrictionU2fIDParams contains all the parameters to send to the API endpoint
for the put me access restriction u2f ID operation typically these are written to a http.Request
*/
type PutMeAccessRestrictionU2fIDParams struct {

	/*ID*/
	ID int64
	/*MeAccessRestrictionU2fPut*/
	MeAccessRestrictionU2fPut *models.NichandleAccessRestrictionU2FAccount

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put me access restriction u2f ID params
func (o *PutMeAccessRestrictionU2fIDParams) WithTimeout(timeout time.Duration) *PutMeAccessRestrictionU2fIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put me access restriction u2f ID params
func (o *PutMeAccessRestrictionU2fIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put me access restriction u2f ID params
func (o *PutMeAccessRestrictionU2fIDParams) WithContext(ctx context.Context) *PutMeAccessRestrictionU2fIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put me access restriction u2f ID params
func (o *PutMeAccessRestrictionU2fIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put me access restriction u2f ID params
func (o *PutMeAccessRestrictionU2fIDParams) WithHTTPClient(client *http.Client) *PutMeAccessRestrictionU2fIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put me access restriction u2f ID params
func (o *PutMeAccessRestrictionU2fIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the put me access restriction u2f ID params
func (o *PutMeAccessRestrictionU2fIDParams) WithID(id int64) *PutMeAccessRestrictionU2fIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put me access restriction u2f ID params
func (o *PutMeAccessRestrictionU2fIDParams) SetID(id int64) {
	o.ID = id
}

// WithMeAccessRestrictionU2fPut adds the meAccessRestrictionU2fPut to the put me access restriction u2f ID params
func (o *PutMeAccessRestrictionU2fIDParams) WithMeAccessRestrictionU2fPut(meAccessRestrictionU2fPut *models.NichandleAccessRestrictionU2FAccount) *PutMeAccessRestrictionU2fIDParams {
	o.SetMeAccessRestrictionU2fPut(meAccessRestrictionU2fPut)
	return o
}

// SetMeAccessRestrictionU2fPut adds the meAccessRestrictionU2fPut to the put me access restriction u2f ID params
func (o *PutMeAccessRestrictionU2fIDParams) SetMeAccessRestrictionU2fPut(meAccessRestrictionU2fPut *models.NichandleAccessRestrictionU2FAccount) {
	o.MeAccessRestrictionU2fPut = meAccessRestrictionU2fPut
}

// WriteToRequest writes these params to a swagger request
func (o *PutMeAccessRestrictionU2fIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if o.MeAccessRestrictionU2fPut != nil {
		if err := r.SetBodyParam(o.MeAccessRestrictionU2fPut); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
