// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017 The go-ovh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/appscode/go-ovh/me/models"
)

// NewPutMePaymentMeanCreditCardIDParams creates a new PutMePaymentMeanCreditCardIDParams object
// with the default values initialized.
func NewPutMePaymentMeanCreditCardIDParams() *PutMePaymentMeanCreditCardIDParams {
	var ()
	return &PutMePaymentMeanCreditCardIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutMePaymentMeanCreditCardIDParamsWithTimeout creates a new PutMePaymentMeanCreditCardIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutMePaymentMeanCreditCardIDParamsWithTimeout(timeout time.Duration) *PutMePaymentMeanCreditCardIDParams {
	var ()
	return &PutMePaymentMeanCreditCardIDParams{

		timeout: timeout,
	}
}

// NewPutMePaymentMeanCreditCardIDParamsWithContext creates a new PutMePaymentMeanCreditCardIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutMePaymentMeanCreditCardIDParamsWithContext(ctx context.Context) *PutMePaymentMeanCreditCardIDParams {
	var ()
	return &PutMePaymentMeanCreditCardIDParams{

		Context: ctx,
	}
}

// NewPutMePaymentMeanCreditCardIDParamsWithHTTPClient creates a new PutMePaymentMeanCreditCardIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutMePaymentMeanCreditCardIDParamsWithHTTPClient(client *http.Client) *PutMePaymentMeanCreditCardIDParams {
	var ()
	return &PutMePaymentMeanCreditCardIDParams{
		HTTPClient: client,
	}
}

/*PutMePaymentMeanCreditCardIDParams contains all the parameters to send to the API endpoint
for the put me payment mean credit card ID operation typically these are written to a http.Request
*/
type PutMePaymentMeanCreditCardIDParams struct {

	/*ID*/
	ID int64
	/*MePaymentMeanCreditCardPut*/
	MePaymentMeanCreditCardPut *models.BillingCreditCard

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put me payment mean credit card ID params
func (o *PutMePaymentMeanCreditCardIDParams) WithTimeout(timeout time.Duration) *PutMePaymentMeanCreditCardIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put me payment mean credit card ID params
func (o *PutMePaymentMeanCreditCardIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put me payment mean credit card ID params
func (o *PutMePaymentMeanCreditCardIDParams) WithContext(ctx context.Context) *PutMePaymentMeanCreditCardIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put me payment mean credit card ID params
func (o *PutMePaymentMeanCreditCardIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put me payment mean credit card ID params
func (o *PutMePaymentMeanCreditCardIDParams) WithHTTPClient(client *http.Client) *PutMePaymentMeanCreditCardIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put me payment mean credit card ID params
func (o *PutMePaymentMeanCreditCardIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the put me payment mean credit card ID params
func (o *PutMePaymentMeanCreditCardIDParams) WithID(id int64) *PutMePaymentMeanCreditCardIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put me payment mean credit card ID params
func (o *PutMePaymentMeanCreditCardIDParams) SetID(id int64) {
	o.ID = id
}

// WithMePaymentMeanCreditCardPut adds the mePaymentMeanCreditCardPut to the put me payment mean credit card ID params
func (o *PutMePaymentMeanCreditCardIDParams) WithMePaymentMeanCreditCardPut(mePaymentMeanCreditCardPut *models.BillingCreditCard) *PutMePaymentMeanCreditCardIDParams {
	o.SetMePaymentMeanCreditCardPut(mePaymentMeanCreditCardPut)
	return o
}

// SetMePaymentMeanCreditCardPut adds the mePaymentMeanCreditCardPut to the put me payment mean credit card ID params
func (o *PutMePaymentMeanCreditCardIDParams) SetMePaymentMeanCreditCardPut(mePaymentMeanCreditCardPut *models.BillingCreditCard) {
	o.MePaymentMeanCreditCardPut = mePaymentMeanCreditCardPut
}

// WriteToRequest writes these params to a swagger request
func (o *PutMePaymentMeanCreditCardIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if o.MePaymentMeanCreditCardPut != nil {
		if err := r.SetBodyParam(o.MePaymentMeanCreditCardPut); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
