// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017 The go-ovh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AgreementsContract Contract of service
// swagger:model agreements.Contract
type AgreementsContract struct {

	// Is this contract currently active or not ?
	// Required: true
	// Read Only: true
	Active bool `json:"active"`

	// Date the contract was created on
	// Required: true
	// Read Only: true
	Date strfmt.Date `json:"date"`

	// Name of of the contract
	// Required: true
	// Read Only: true
	Name string `json:"name"`

	// URL you can download the contract at
	// Required: true
	// Read Only: true
	Pdf string `json:"pdf"`

	// Full text of the contract
	// Required: true
	// Read Only: true
	Text string `json:"text"`
}

// Validate validates this agreements contract
func (m *AgreementsContract) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateActive(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateDate(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validatePdf(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateText(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AgreementsContract) validateActive(formats strfmt.Registry) error {

	if err := validate.Required("active", "body", bool(m.Active)); err != nil {
		return err
	}

	return nil
}

func (m *AgreementsContract) validateDate(formats strfmt.Registry) error {

	if err := validate.Required("date", "body", strfmt.Date(m.Date)); err != nil {
		return err
	}

	if err := validate.FormatOf("date", "body", "date", m.Date.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *AgreementsContract) validateName(formats strfmt.Registry) error {

	if err := validate.RequiredString("name", "body", string(m.Name)); err != nil {
		return err
	}

	return nil
}

func (m *AgreementsContract) validatePdf(formats strfmt.Registry) error {

	if err := validate.RequiredString("pdf", "body", string(m.Pdf)); err != nil {
		return err
	}

	return nil
}

func (m *AgreementsContract) validateText(formats strfmt.Registry) error {

	if err := validate.RequiredString("text", "body", string(m.Text)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AgreementsContract) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AgreementsContract) UnmarshalBinary(b []byte) error {
	var res AgreementsContract
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
