// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017 The go-ovh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// APILog API Log
// swagger:model api.Log
type APILog struct {

	// Account which did the Request
	// Required: true
	// Read Only: true
	Account string `json:"account"`

	// Date of the request
	// Required: true
	// Read Only: true
	Date strfmt.DateTime `json:"date"`

	// Source IP of the request
	// Read Only: true
	IP string `json:"ip,omitempty"`

	// log Id
	// Required: true
	// Read Only: true
	LogID int64 `json:"logId"`

	// HTTP Method of the request
	// Required: true
	// Read Only: true
	Method string `json:"method"`

	// HTTP URI of the request
	// Required: true
	// Read Only: true
	Path string `json:"path"`

	// API Route called
	// Required: true
	// Read Only: true
	Route string `json:"route"`
}

// Validate validates this api log
func (m *APILog) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAccount(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateDate(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateLogID(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateMethod(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validatePath(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateRoute(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APILog) validateAccount(formats strfmt.Registry) error {

	if err := validate.RequiredString("account", "body", string(m.Account)); err != nil {
		return err
	}

	return nil
}

func (m *APILog) validateDate(formats strfmt.Registry) error {

	if err := validate.Required("date", "body", strfmt.DateTime(m.Date)); err != nil {
		return err
	}

	if err := validate.FormatOf("date", "body", "date-time", m.Date.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *APILog) validateLogID(formats strfmt.Registry) error {

	if err := validate.Required("logId", "body", int64(m.LogID)); err != nil {
		return err
	}

	return nil
}

var apiLogTypeMethodPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["DELETE","GET","POST","PUT"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		apiLogTypeMethodPropEnum = append(apiLogTypeMethodPropEnum, v)
	}
}

const (
	// APILogMethodDELETE captures enum value "DELETE"
	APILogMethodDELETE string = "DELETE"
	// APILogMethodGET captures enum value "GET"
	APILogMethodGET string = "GET"
	// APILogMethodPOST captures enum value "POST"
	APILogMethodPOST string = "POST"
	// APILogMethodPUT captures enum value "PUT"
	APILogMethodPUT string = "PUT"
)

// prop value enum
func (m *APILog) validateMethodEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, apiLogTypeMethodPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *APILog) validateMethod(formats strfmt.Registry) error {

	if err := validate.RequiredString("method", "body", string(m.Method)); err != nil {
		return err
	}

	// value enum
	if err := m.validateMethodEnum("method", "body", m.Method); err != nil {
		return err
	}

	return nil
}

func (m *APILog) validatePath(formats strfmt.Registry) error {

	if err := validate.RequiredString("path", "body", string(m.Path)); err != nil {
		return err
	}

	return nil
}

func (m *APILog) validateRoute(formats strfmt.Registry) error {

	if err := validate.RequiredString("route", "body", string(m.Route)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *APILog) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APILog) UnmarshalBinary(b []byte) error {
	var res APILog
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
