// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017 The go-ovh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// BillingItemDetailOrder Order data for this Detail
// swagger:model billing.ItemDetail.Order
type BillingItemDetailOrder struct {

	// The meaning of this order detail
	Action string `json:"action,omitempty"`

	// configurations
	Configurations BillingItemDetailOrderConfigurations `json:"configurations"`

	// plan
	Plan *BillingItemDetailOrderPlan `json:"plan,omitempty"`
}

// Validate validates this billing item detail order
func (m *BillingItemDetailOrder) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAction(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validatePlan(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var billingItemDetailOrderTypeActionPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["consumption","installation","renew","upgrade"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		billingItemDetailOrderTypeActionPropEnum = append(billingItemDetailOrderTypeActionPropEnum, v)
	}
}

const (
	// BillingItemDetailOrderActionConsumption captures enum value "consumption"
	BillingItemDetailOrderActionConsumption string = "consumption"
	// BillingItemDetailOrderActionInstallation captures enum value "installation"
	BillingItemDetailOrderActionInstallation string = "installation"
	// BillingItemDetailOrderActionRenew captures enum value "renew"
	BillingItemDetailOrderActionRenew string = "renew"
	// BillingItemDetailOrderActionUpgrade captures enum value "upgrade"
	BillingItemDetailOrderActionUpgrade string = "upgrade"
)

// prop value enum
func (m *BillingItemDetailOrder) validateActionEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, billingItemDetailOrderTypeActionPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *BillingItemDetailOrder) validateAction(formats strfmt.Registry) error {

	if swag.IsZero(m.Action) { // not required
		return nil
	}

	// value enum
	if err := m.validateActionEnum("action", "body", m.Action); err != nil {
		return err
	}

	return nil
}

func (m *BillingItemDetailOrder) validatePlan(formats strfmt.Registry) error {

	if swag.IsZero(m.Plan) { // not required
		return nil
	}

	if m.Plan != nil {

		if err := m.Plan.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("plan")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *BillingItemDetailOrder) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BillingItemDetailOrder) UnmarshalBinary(b []byte) error {
	var res BillingItemDetailOrder
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
