// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017 The go-ovh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteCloudProjectServiceNameIPLoadbalancingIDParams creates a new DeleteCloudProjectServiceNameIPLoadbalancingIDParams object
// with the default values initialized.
func NewDeleteCloudProjectServiceNameIPLoadbalancingIDParams() *DeleteCloudProjectServiceNameIPLoadbalancingIDParams {
	var ()
	return &DeleteCloudProjectServiceNameIPLoadbalancingIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteCloudProjectServiceNameIPLoadbalancingIDParamsWithTimeout creates a new DeleteCloudProjectServiceNameIPLoadbalancingIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteCloudProjectServiceNameIPLoadbalancingIDParamsWithTimeout(timeout time.Duration) *DeleteCloudProjectServiceNameIPLoadbalancingIDParams {
	var ()
	return &DeleteCloudProjectServiceNameIPLoadbalancingIDParams{

		timeout: timeout,
	}
}

// NewDeleteCloudProjectServiceNameIPLoadbalancingIDParamsWithContext creates a new DeleteCloudProjectServiceNameIPLoadbalancingIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteCloudProjectServiceNameIPLoadbalancingIDParamsWithContext(ctx context.Context) *DeleteCloudProjectServiceNameIPLoadbalancingIDParams {
	var ()
	return &DeleteCloudProjectServiceNameIPLoadbalancingIDParams{

		Context: ctx,
	}
}

// NewDeleteCloudProjectServiceNameIPLoadbalancingIDParamsWithHTTPClient creates a new DeleteCloudProjectServiceNameIPLoadbalancingIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteCloudProjectServiceNameIPLoadbalancingIDParamsWithHTTPClient(client *http.Client) *DeleteCloudProjectServiceNameIPLoadbalancingIDParams {
	var ()
	return &DeleteCloudProjectServiceNameIPLoadbalancingIDParams{
		HTTPClient: client,
	}
}

/*DeleteCloudProjectServiceNameIPLoadbalancingIDParams contains all the parameters to send to the API endpoint
for the delete cloud project service name IP loadbalancing ID operation typically these are written to a http.Request
*/
type DeleteCloudProjectServiceNameIPLoadbalancingIDParams struct {

	/*ID*/
	ID string
	/*ServiceName*/
	ServiceName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete cloud project service name IP loadbalancing ID params
func (o *DeleteCloudProjectServiceNameIPLoadbalancingIDParams) WithTimeout(timeout time.Duration) *DeleteCloudProjectServiceNameIPLoadbalancingIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete cloud project service name IP loadbalancing ID params
func (o *DeleteCloudProjectServiceNameIPLoadbalancingIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete cloud project service name IP loadbalancing ID params
func (o *DeleteCloudProjectServiceNameIPLoadbalancingIDParams) WithContext(ctx context.Context) *DeleteCloudProjectServiceNameIPLoadbalancingIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete cloud project service name IP loadbalancing ID params
func (o *DeleteCloudProjectServiceNameIPLoadbalancingIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete cloud project service name IP loadbalancing ID params
func (o *DeleteCloudProjectServiceNameIPLoadbalancingIDParams) WithHTTPClient(client *http.Client) *DeleteCloudProjectServiceNameIPLoadbalancingIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete cloud project service name IP loadbalancing ID params
func (o *DeleteCloudProjectServiceNameIPLoadbalancingIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete cloud project service name IP loadbalancing ID params
func (o *DeleteCloudProjectServiceNameIPLoadbalancingIDParams) WithID(id string) *DeleteCloudProjectServiceNameIPLoadbalancingIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete cloud project service name IP loadbalancing ID params
func (o *DeleteCloudProjectServiceNameIPLoadbalancingIDParams) SetID(id string) {
	o.ID = id
}

// WithServiceName adds the serviceName to the delete cloud project service name IP loadbalancing ID params
func (o *DeleteCloudProjectServiceNameIPLoadbalancingIDParams) WithServiceName(serviceName string) *DeleteCloudProjectServiceNameIPLoadbalancingIDParams {
	o.SetServiceName(serviceName)
	return o
}

// SetServiceName adds the serviceName to the delete cloud project service name IP loadbalancing ID params
func (o *DeleteCloudProjectServiceNameIPLoadbalancingIDParams) SetServiceName(serviceName string) {
	o.ServiceName = serviceName
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteCloudProjectServiceNameIPLoadbalancingIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param serviceName
	if err := r.SetPathParam("serviceName", o.ServiceName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
