// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017 The go-ovh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/appscode/go-ovh/cloud/models"
)

// GetCloudProjectServiceNameInstanceInstanceIDReader is a Reader for the GetCloudProjectServiceNameInstanceInstanceID structure.
type GetCloudProjectServiceNameInstanceInstanceIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCloudProjectServiceNameInstanceInstanceIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetCloudProjectServiceNameInstanceInstanceIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetCloudProjectServiceNameInstanceInstanceIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetCloudProjectServiceNameInstanceInstanceIDOK creates a GetCloudProjectServiceNameInstanceInstanceIDOK with default headers values
func NewGetCloudProjectServiceNameInstanceInstanceIDOK() *GetCloudProjectServiceNameInstanceInstanceIDOK {
	return &GetCloudProjectServiceNameInstanceInstanceIDOK{}
}

/*GetCloudProjectServiceNameInstanceInstanceIDOK handles this case with default header values.

description of 'cloud.Instance.InstanceDetail' response
*/
type GetCloudProjectServiceNameInstanceInstanceIDOK struct {
	Payload *models.CloudInstanceInstanceDetail
}

func (o *GetCloudProjectServiceNameInstanceInstanceIDOK) Error() string {
	return fmt.Sprintf("[GET /cloud/project/{serviceName}/instance/{instanceId}][%d] getCloudProjectServiceNameInstanceInstanceIdOK  %+v", 200, o.Payload)
}

func (o *GetCloudProjectServiceNameInstanceInstanceIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CloudInstanceInstanceDetail)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCloudProjectServiceNameInstanceInstanceIDDefault creates a GetCloudProjectServiceNameInstanceInstanceIDDefault with default headers values
func NewGetCloudProjectServiceNameInstanceInstanceIDDefault(code int) *GetCloudProjectServiceNameInstanceInstanceIDDefault {
	return &GetCloudProjectServiceNameInstanceInstanceIDDefault{
		_statusCode: code,
	}
}

/*GetCloudProjectServiceNameInstanceInstanceIDDefault handles this case with default header values.

Unexpected error
*/
type GetCloudProjectServiceNameInstanceInstanceIDDefault struct {
	_statusCode int

	Payload *models.GetCloudProjectServiceNameInstanceInstanceIDDefaultBody
}

// Code gets the status code for the get cloud project service name instance instance ID default response
func (o *GetCloudProjectServiceNameInstanceInstanceIDDefault) Code() int {
	return o._statusCode
}

func (o *GetCloudProjectServiceNameInstanceInstanceIDDefault) Error() string {
	return fmt.Sprintf("[GET /cloud/project/{serviceName}/instance/{instanceId}][%d] GetCloudProjectServiceNameInstanceInstanceID default  %+v", o._statusCode, o.Payload)
}

func (o *GetCloudProjectServiceNameInstanceInstanceIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetCloudProjectServiceNameInstanceInstanceIDDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
