// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017 The go-ovh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/appscode/go-ovh/cloud/models"
)

// GetCloudProjectServiceNameVolumeReader is a Reader for the GetCloudProjectServiceNameVolume structure.
type GetCloudProjectServiceNameVolumeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCloudProjectServiceNameVolumeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetCloudProjectServiceNameVolumeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetCloudProjectServiceNameVolumeDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetCloudProjectServiceNameVolumeOK creates a GetCloudProjectServiceNameVolumeOK with default headers values
func NewGetCloudProjectServiceNameVolumeOK() *GetCloudProjectServiceNameVolumeOK {
	return &GetCloudProjectServiceNameVolumeOK{}
}

/*GetCloudProjectServiceNameVolumeOK handles this case with default header values.

return value
*/
type GetCloudProjectServiceNameVolumeOK struct {
	Payload models.GetCloudProjectServiceNameVolumeOKBody
}

func (o *GetCloudProjectServiceNameVolumeOK) Error() string {
	return fmt.Sprintf("[GET /cloud/project/{serviceName}/volume][%d] getCloudProjectServiceNameVolumeOK  %+v", 200, o.Payload)
}

func (o *GetCloudProjectServiceNameVolumeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCloudProjectServiceNameVolumeDefault creates a GetCloudProjectServiceNameVolumeDefault with default headers values
func NewGetCloudProjectServiceNameVolumeDefault(code int) *GetCloudProjectServiceNameVolumeDefault {
	return &GetCloudProjectServiceNameVolumeDefault{
		_statusCode: code,
	}
}

/*GetCloudProjectServiceNameVolumeDefault handles this case with default header values.

Unexpected error
*/
type GetCloudProjectServiceNameVolumeDefault struct {
	_statusCode int

	Payload *models.GetCloudProjectServiceNameVolumeDefaultBody
}

// Code gets the status code for the get cloud project service name volume default response
func (o *GetCloudProjectServiceNameVolumeDefault) Code() int {
	return o._statusCode
}

func (o *GetCloudProjectServiceNameVolumeDefault) Error() string {
	return fmt.Sprintf("[GET /cloud/project/{serviceName}/volume][%d] GetCloudProjectServiceNameVolume default  %+v", o._statusCode, o.Payload)
}

func (o *GetCloudProjectServiceNameVolumeDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetCloudProjectServiceNameVolumeDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
