// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017 The go-ovh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCloudProjectServiceNameRegionRegionNameParams creates a new GetCloudProjectServiceNameRegionRegionNameParams object
// with the default values initialized.
func NewGetCloudProjectServiceNameRegionRegionNameParams() *GetCloudProjectServiceNameRegionRegionNameParams {
	var ()
	return &GetCloudProjectServiceNameRegionRegionNameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCloudProjectServiceNameRegionRegionNameParamsWithTimeout creates a new GetCloudProjectServiceNameRegionRegionNameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCloudProjectServiceNameRegionRegionNameParamsWithTimeout(timeout time.Duration) *GetCloudProjectServiceNameRegionRegionNameParams {
	var ()
	return &GetCloudProjectServiceNameRegionRegionNameParams{

		timeout: timeout,
	}
}

// NewGetCloudProjectServiceNameRegionRegionNameParamsWithContext creates a new GetCloudProjectServiceNameRegionRegionNameParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCloudProjectServiceNameRegionRegionNameParamsWithContext(ctx context.Context) *GetCloudProjectServiceNameRegionRegionNameParams {
	var ()
	return &GetCloudProjectServiceNameRegionRegionNameParams{

		Context: ctx,
	}
}

// NewGetCloudProjectServiceNameRegionRegionNameParamsWithHTTPClient creates a new GetCloudProjectServiceNameRegionRegionNameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCloudProjectServiceNameRegionRegionNameParamsWithHTTPClient(client *http.Client) *GetCloudProjectServiceNameRegionRegionNameParams {
	var ()
	return &GetCloudProjectServiceNameRegionRegionNameParams{
		HTTPClient: client,
	}
}

/*GetCloudProjectServiceNameRegionRegionNameParams contains all the parameters to send to the API endpoint
for the get cloud project service name region region name operation typically these are written to a http.Request
*/
type GetCloudProjectServiceNameRegionRegionNameParams struct {

	/*RegionName*/
	RegionName string
	/*ServiceName*/
	ServiceName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get cloud project service name region region name params
func (o *GetCloudProjectServiceNameRegionRegionNameParams) WithTimeout(timeout time.Duration) *GetCloudProjectServiceNameRegionRegionNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get cloud project service name region region name params
func (o *GetCloudProjectServiceNameRegionRegionNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get cloud project service name region region name params
func (o *GetCloudProjectServiceNameRegionRegionNameParams) WithContext(ctx context.Context) *GetCloudProjectServiceNameRegionRegionNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get cloud project service name region region name params
func (o *GetCloudProjectServiceNameRegionRegionNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get cloud project service name region region name params
func (o *GetCloudProjectServiceNameRegionRegionNameParams) WithHTTPClient(client *http.Client) *GetCloudProjectServiceNameRegionRegionNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get cloud project service name region region name params
func (o *GetCloudProjectServiceNameRegionRegionNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRegionName adds the regionName to the get cloud project service name region region name params
func (o *GetCloudProjectServiceNameRegionRegionNameParams) WithRegionName(regionName string) *GetCloudProjectServiceNameRegionRegionNameParams {
	o.SetRegionName(regionName)
	return o
}

// SetRegionName adds the regionName to the get cloud project service name region region name params
func (o *GetCloudProjectServiceNameRegionRegionNameParams) SetRegionName(regionName string) {
	o.RegionName = regionName
}

// WithServiceName adds the serviceName to the get cloud project service name region region name params
func (o *GetCloudProjectServiceNameRegionRegionNameParams) WithServiceName(serviceName string) *GetCloudProjectServiceNameRegionRegionNameParams {
	o.SetServiceName(serviceName)
	return o
}

// SetServiceName adds the serviceName to the get cloud project service name region region name params
func (o *GetCloudProjectServiceNameRegionRegionNameParams) SetServiceName(serviceName string) {
	o.ServiceName = serviceName
}

// WriteToRequest writes these params to a swagger request
func (o *GetCloudProjectServiceNameRegionRegionNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param regionName
	if err := r.SetPathParam("regionName", o.RegionName); err != nil {
		return err
	}

	// path param serviceName
	if err := r.SetPathParam("serviceName", o.ServiceName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
