// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017 The go-ovh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/appscode/go-ovh/cloud/models"
)

// GetCloudProjectServiceNameAlertingIDReader is a Reader for the GetCloudProjectServiceNameAlertingID structure.
type GetCloudProjectServiceNameAlertingIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCloudProjectServiceNameAlertingIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetCloudProjectServiceNameAlertingIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetCloudProjectServiceNameAlertingIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetCloudProjectServiceNameAlertingIDOK creates a GetCloudProjectServiceNameAlertingIDOK with default headers values
func NewGetCloudProjectServiceNameAlertingIDOK() *GetCloudProjectServiceNameAlertingIDOK {
	return &GetCloudProjectServiceNameAlertingIDOK{}
}

/*GetCloudProjectServiceNameAlertingIDOK handles this case with default header values.

description of 'cloud.Alerting' response
*/
type GetCloudProjectServiceNameAlertingIDOK struct {
	Payload *models.CloudAlerting
}

func (o *GetCloudProjectServiceNameAlertingIDOK) Error() string {
	return fmt.Sprintf("[GET /cloud/project/{serviceName}/alerting/{id}][%d] getCloudProjectServiceNameAlertingIdOK  %+v", 200, o.Payload)
}

func (o *GetCloudProjectServiceNameAlertingIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CloudAlerting)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCloudProjectServiceNameAlertingIDDefault creates a GetCloudProjectServiceNameAlertingIDDefault with default headers values
func NewGetCloudProjectServiceNameAlertingIDDefault(code int) *GetCloudProjectServiceNameAlertingIDDefault {
	return &GetCloudProjectServiceNameAlertingIDDefault{
		_statusCode: code,
	}
}

/*GetCloudProjectServiceNameAlertingIDDefault handles this case with default header values.

Unexpected error
*/
type GetCloudProjectServiceNameAlertingIDDefault struct {
	_statusCode int

	Payload *models.GetCloudProjectServiceNameAlertingIDDefaultBody
}

// Code gets the status code for the get cloud project service name alerting ID default response
func (o *GetCloudProjectServiceNameAlertingIDDefault) Code() int {
	return o._statusCode
}

func (o *GetCloudProjectServiceNameAlertingIDDefault) Error() string {
	return fmt.Sprintf("[GET /cloud/project/{serviceName}/alerting/{id}][%d] GetCloudProjectServiceNameAlertingID default  %+v", o._statusCode, o.Payload)
}

func (o *GetCloudProjectServiceNameAlertingIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetCloudProjectServiceNameAlertingIDDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
