// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017 The go-ovh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/appscode/go-ovh/cloud/models"
)

// GetCloudProjectServiceNameStorageAccessReader is a Reader for the GetCloudProjectServiceNameStorageAccess structure.
type GetCloudProjectServiceNameStorageAccessReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCloudProjectServiceNameStorageAccessReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetCloudProjectServiceNameStorageAccessOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetCloudProjectServiceNameStorageAccessDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetCloudProjectServiceNameStorageAccessOK creates a GetCloudProjectServiceNameStorageAccessOK with default headers values
func NewGetCloudProjectServiceNameStorageAccessOK() *GetCloudProjectServiceNameStorageAccessOK {
	return &GetCloudProjectServiceNameStorageAccessOK{}
}

/*GetCloudProjectServiceNameStorageAccessOK handles this case with default header values.

description of 'cloud.Storage.ContainerAccess' response
*/
type GetCloudProjectServiceNameStorageAccessOK struct {
	Payload *models.CloudStorageContainerAccess
}

func (o *GetCloudProjectServiceNameStorageAccessOK) Error() string {
	return fmt.Sprintf("[GET /cloud/project/{serviceName}/storage/access][%d] getCloudProjectServiceNameStorageAccessOK  %+v", 200, o.Payload)
}

func (o *GetCloudProjectServiceNameStorageAccessOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CloudStorageContainerAccess)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCloudProjectServiceNameStorageAccessDefault creates a GetCloudProjectServiceNameStorageAccessDefault with default headers values
func NewGetCloudProjectServiceNameStorageAccessDefault(code int) *GetCloudProjectServiceNameStorageAccessDefault {
	return &GetCloudProjectServiceNameStorageAccessDefault{
		_statusCode: code,
	}
}

/*GetCloudProjectServiceNameStorageAccessDefault handles this case with default header values.

Unexpected error
*/
type GetCloudProjectServiceNameStorageAccessDefault struct {
	_statusCode int

	Payload *models.GetCloudProjectServiceNameStorageAccessDefaultBody
}

// Code gets the status code for the get cloud project service name storage access default response
func (o *GetCloudProjectServiceNameStorageAccessDefault) Code() int {
	return o._statusCode
}

func (o *GetCloudProjectServiceNameStorageAccessDefault) Error() string {
	return fmt.Sprintf("[GET /cloud/project/{serviceName}/storage/access][%d] GetCloudProjectServiceNameStorageAccess default  %+v", o._statusCode, o.Payload)
}

func (o *GetCloudProjectServiceNameStorageAccessDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetCloudProjectServiceNameStorageAccessDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
