// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017 The go-ovh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/appscode/go-ovh/cloud/models"
)

// PostCloudProjectServiceNameStorageContainerIDCorsReader is a Reader for the PostCloudProjectServiceNameStorageContainerIDCors structure.
type PostCloudProjectServiceNameStorageContainerIDCorsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostCloudProjectServiceNameStorageContainerIDCorsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostCloudProjectServiceNameStorageContainerIDCorsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewPostCloudProjectServiceNameStorageContainerIDCorsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostCloudProjectServiceNameStorageContainerIDCorsOK creates a PostCloudProjectServiceNameStorageContainerIDCorsOK with default headers values
func NewPostCloudProjectServiceNameStorageContainerIDCorsOK() *PostCloudProjectServiceNameStorageContainerIDCorsOK {
	return &PostCloudProjectServiceNameStorageContainerIDCorsOK{}
}

/*PostCloudProjectServiceNameStorageContainerIDCorsOK handles this case with default header values.

return 'void'
*/
type PostCloudProjectServiceNameStorageContainerIDCorsOK struct {
}

func (o *PostCloudProjectServiceNameStorageContainerIDCorsOK) Error() string {
	return fmt.Sprintf("[POST /cloud/project/{serviceName}/storage/{containerId}/cors][%d] postCloudProjectServiceNameStorageContainerIdCorsOK ", 200)
}

func (o *PostCloudProjectServiceNameStorageContainerIDCorsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostCloudProjectServiceNameStorageContainerIDCorsDefault creates a PostCloudProjectServiceNameStorageContainerIDCorsDefault with default headers values
func NewPostCloudProjectServiceNameStorageContainerIDCorsDefault(code int) *PostCloudProjectServiceNameStorageContainerIDCorsDefault {
	return &PostCloudProjectServiceNameStorageContainerIDCorsDefault{
		_statusCode: code,
	}
}

/*PostCloudProjectServiceNameStorageContainerIDCorsDefault handles this case with default header values.

Unexpected error
*/
type PostCloudProjectServiceNameStorageContainerIDCorsDefault struct {
	_statusCode int

	Payload *models.PostCloudProjectServiceNameStorageContainerIDCorsDefaultBody
}

// Code gets the status code for the post cloud project service name storage container ID cors default response
func (o *PostCloudProjectServiceNameStorageContainerIDCorsDefault) Code() int {
	return o._statusCode
}

func (o *PostCloudProjectServiceNameStorageContainerIDCorsDefault) Error() string {
	return fmt.Sprintf("[POST /cloud/project/{serviceName}/storage/{containerId}/cors][%d] PostCloudProjectServiceNameStorageContainerIDCors default  %+v", o._statusCode, o.Payload)
}

func (o *PostCloudProjectServiceNameStorageContainerIDCorsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PostCloudProjectServiceNameStorageContainerIDCorsDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
