// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017 The go-ovh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/appscode/go-ovh/cloud/models"
)

// PostCloudProjectServiceNameInstanceGroupReader is a Reader for the PostCloudProjectServiceNameInstanceGroup structure.
type PostCloudProjectServiceNameInstanceGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostCloudProjectServiceNameInstanceGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostCloudProjectServiceNameInstanceGroupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewPostCloudProjectServiceNameInstanceGroupDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostCloudProjectServiceNameInstanceGroupOK creates a PostCloudProjectServiceNameInstanceGroupOK with default headers values
func NewPostCloudProjectServiceNameInstanceGroupOK() *PostCloudProjectServiceNameInstanceGroupOK {
	return &PostCloudProjectServiceNameInstanceGroupOK{}
}

/*PostCloudProjectServiceNameInstanceGroupOK handles this case with default header values.

description of 'cloud.Instancegroup.InstanceGroup' response
*/
type PostCloudProjectServiceNameInstanceGroupOK struct {
	Payload *models.CloudInstancegroupInstanceGroup
}

func (o *PostCloudProjectServiceNameInstanceGroupOK) Error() string {
	return fmt.Sprintf("[POST /cloud/project/{serviceName}/instance/group][%d] postCloudProjectServiceNameInstanceGroupOK  %+v", 200, o.Payload)
}

func (o *PostCloudProjectServiceNameInstanceGroupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CloudInstancegroupInstanceGroup)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostCloudProjectServiceNameInstanceGroupDefault creates a PostCloudProjectServiceNameInstanceGroupDefault with default headers values
func NewPostCloudProjectServiceNameInstanceGroupDefault(code int) *PostCloudProjectServiceNameInstanceGroupDefault {
	return &PostCloudProjectServiceNameInstanceGroupDefault{
		_statusCode: code,
	}
}

/*PostCloudProjectServiceNameInstanceGroupDefault handles this case with default header values.

Unexpected error
*/
type PostCloudProjectServiceNameInstanceGroupDefault struct {
	_statusCode int

	Payload *models.PostCloudProjectServiceNameInstanceGroupDefaultBody
}

// Code gets the status code for the post cloud project service name instance group default response
func (o *PostCloudProjectServiceNameInstanceGroupDefault) Code() int {
	return o._statusCode
}

func (o *PostCloudProjectServiceNameInstanceGroupDefault) Error() string {
	return fmt.Sprintf("[POST /cloud/project/{serviceName}/instance/group][%d] PostCloudProjectServiceNameInstanceGroup default  %+v", o._statusCode, o.Payload)
}

func (o *PostCloudProjectServiceNameInstanceGroupDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PostCloudProjectServiceNameInstanceGroupDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
