// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017 The go-ovh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteIPLoadbalancingServiceNameHTTPRouteRouteIDRuleRuleIDParams creates a new DeleteIPLoadbalancingServiceNameHTTPRouteRouteIDRuleRuleIDParams object
// with the default values initialized.
func NewDeleteIPLoadbalancingServiceNameHTTPRouteRouteIDRuleRuleIDParams() *DeleteIPLoadbalancingServiceNameHTTPRouteRouteIDRuleRuleIDParams {
	var ()
	return &DeleteIPLoadbalancingServiceNameHTTPRouteRouteIDRuleRuleIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteIPLoadbalancingServiceNameHTTPRouteRouteIDRuleRuleIDParamsWithTimeout creates a new DeleteIPLoadbalancingServiceNameHTTPRouteRouteIDRuleRuleIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteIPLoadbalancingServiceNameHTTPRouteRouteIDRuleRuleIDParamsWithTimeout(timeout time.Duration) *DeleteIPLoadbalancingServiceNameHTTPRouteRouteIDRuleRuleIDParams {
	var ()
	return &DeleteIPLoadbalancingServiceNameHTTPRouteRouteIDRuleRuleIDParams{

		timeout: timeout,
	}
}

// NewDeleteIPLoadbalancingServiceNameHTTPRouteRouteIDRuleRuleIDParamsWithContext creates a new DeleteIPLoadbalancingServiceNameHTTPRouteRouteIDRuleRuleIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteIPLoadbalancingServiceNameHTTPRouteRouteIDRuleRuleIDParamsWithContext(ctx context.Context) *DeleteIPLoadbalancingServiceNameHTTPRouteRouteIDRuleRuleIDParams {
	var ()
	return &DeleteIPLoadbalancingServiceNameHTTPRouteRouteIDRuleRuleIDParams{

		Context: ctx,
	}
}

// NewDeleteIPLoadbalancingServiceNameHTTPRouteRouteIDRuleRuleIDParamsWithHTTPClient creates a new DeleteIPLoadbalancingServiceNameHTTPRouteRouteIDRuleRuleIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteIPLoadbalancingServiceNameHTTPRouteRouteIDRuleRuleIDParamsWithHTTPClient(client *http.Client) *DeleteIPLoadbalancingServiceNameHTTPRouteRouteIDRuleRuleIDParams {
	var ()
	return &DeleteIPLoadbalancingServiceNameHTTPRouteRouteIDRuleRuleIDParams{
		HTTPClient: client,
	}
}

/*DeleteIPLoadbalancingServiceNameHTTPRouteRouteIDRuleRuleIDParams contains all the parameters to send to the API endpoint
for the delete IP loadbalancing service name HTTP route route ID rule rule ID operation typically these are written to a http.Request
*/
type DeleteIPLoadbalancingServiceNameHTTPRouteRouteIDRuleRuleIDParams struct {

	/*RouteID*/
	RouteID int64
	/*RuleID*/
	RuleID int64
	/*ServiceName*/
	ServiceName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete IP loadbalancing service name HTTP route route ID rule rule ID params
func (o *DeleteIPLoadbalancingServiceNameHTTPRouteRouteIDRuleRuleIDParams) WithTimeout(timeout time.Duration) *DeleteIPLoadbalancingServiceNameHTTPRouteRouteIDRuleRuleIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete IP loadbalancing service name HTTP route route ID rule rule ID params
func (o *DeleteIPLoadbalancingServiceNameHTTPRouteRouteIDRuleRuleIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete IP loadbalancing service name HTTP route route ID rule rule ID params
func (o *DeleteIPLoadbalancingServiceNameHTTPRouteRouteIDRuleRuleIDParams) WithContext(ctx context.Context) *DeleteIPLoadbalancingServiceNameHTTPRouteRouteIDRuleRuleIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete IP loadbalancing service name HTTP route route ID rule rule ID params
func (o *DeleteIPLoadbalancingServiceNameHTTPRouteRouteIDRuleRuleIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete IP loadbalancing service name HTTP route route ID rule rule ID params
func (o *DeleteIPLoadbalancingServiceNameHTTPRouteRouteIDRuleRuleIDParams) WithHTTPClient(client *http.Client) *DeleteIPLoadbalancingServiceNameHTTPRouteRouteIDRuleRuleIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete IP loadbalancing service name HTTP route route ID rule rule ID params
func (o *DeleteIPLoadbalancingServiceNameHTTPRouteRouteIDRuleRuleIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRouteID adds the routeID to the delete IP loadbalancing service name HTTP route route ID rule rule ID params
func (o *DeleteIPLoadbalancingServiceNameHTTPRouteRouteIDRuleRuleIDParams) WithRouteID(routeID int64) *DeleteIPLoadbalancingServiceNameHTTPRouteRouteIDRuleRuleIDParams {
	o.SetRouteID(routeID)
	return o
}

// SetRouteID adds the routeId to the delete IP loadbalancing service name HTTP route route ID rule rule ID params
func (o *DeleteIPLoadbalancingServiceNameHTTPRouteRouteIDRuleRuleIDParams) SetRouteID(routeID int64) {
	o.RouteID = routeID
}

// WithRuleID adds the ruleID to the delete IP loadbalancing service name HTTP route route ID rule rule ID params
func (o *DeleteIPLoadbalancingServiceNameHTTPRouteRouteIDRuleRuleIDParams) WithRuleID(ruleID int64) *DeleteIPLoadbalancingServiceNameHTTPRouteRouteIDRuleRuleIDParams {
	o.SetRuleID(ruleID)
	return o
}

// SetRuleID adds the ruleId to the delete IP loadbalancing service name HTTP route route ID rule rule ID params
func (o *DeleteIPLoadbalancingServiceNameHTTPRouteRouteIDRuleRuleIDParams) SetRuleID(ruleID int64) {
	o.RuleID = ruleID
}

// WithServiceName adds the serviceName to the delete IP loadbalancing service name HTTP route route ID rule rule ID params
func (o *DeleteIPLoadbalancingServiceNameHTTPRouteRouteIDRuleRuleIDParams) WithServiceName(serviceName string) *DeleteIPLoadbalancingServiceNameHTTPRouteRouteIDRuleRuleIDParams {
	o.SetServiceName(serviceName)
	return o
}

// SetServiceName adds the serviceName to the delete IP loadbalancing service name HTTP route route ID rule rule ID params
func (o *DeleteIPLoadbalancingServiceNameHTTPRouteRouteIDRuleRuleIDParams) SetServiceName(serviceName string) {
	o.ServiceName = serviceName
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteIPLoadbalancingServiceNameHTTPRouteRouteIDRuleRuleIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param routeId
	if err := r.SetPathParam("routeId", swag.FormatInt64(o.RouteID)); err != nil {
		return err
	}

	// path param ruleId
	if err := r.SetPathParam("ruleId", swag.FormatInt64(o.RuleID)); err != nil {
		return err
	}

	// path param serviceName
	if err := r.SetPathParam("serviceName", o.ServiceName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
