// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017 The go-ovh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/appscode/go-ovh/iploadbalancing/models"
)

// GetIPLoadbalancingServiceNameTaskIDReader is a Reader for the GetIPLoadbalancingServiceNameTaskID structure.
type GetIPLoadbalancingServiceNameTaskIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetIPLoadbalancingServiceNameTaskIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetIPLoadbalancingServiceNameTaskIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetIPLoadbalancingServiceNameTaskIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetIPLoadbalancingServiceNameTaskIDOK creates a GetIPLoadbalancingServiceNameTaskIDOK with default headers values
func NewGetIPLoadbalancingServiceNameTaskIDOK() *GetIPLoadbalancingServiceNameTaskIDOK {
	return &GetIPLoadbalancingServiceNameTaskIDOK{}
}

/*GetIPLoadbalancingServiceNameTaskIDOK handles this case with default header values.

description of 'iplb.Task.Task' response
*/
type GetIPLoadbalancingServiceNameTaskIDOK struct {
	Payload *models.IPLBTaskTask
}

func (o *GetIPLoadbalancingServiceNameTaskIDOK) Error() string {
	return fmt.Sprintf("[GET /ipLoadbalancing/{serviceName}/task/{id}][%d] getIpLoadbalancingServiceNameTaskIdOK  %+v", 200, o.Payload)
}

func (o *GetIPLoadbalancingServiceNameTaskIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IPLBTaskTask)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetIPLoadbalancingServiceNameTaskIDDefault creates a GetIPLoadbalancingServiceNameTaskIDDefault with default headers values
func NewGetIPLoadbalancingServiceNameTaskIDDefault(code int) *GetIPLoadbalancingServiceNameTaskIDDefault {
	return &GetIPLoadbalancingServiceNameTaskIDDefault{
		_statusCode: code,
	}
}

/*GetIPLoadbalancingServiceNameTaskIDDefault handles this case with default header values.

Unexpected error
*/
type GetIPLoadbalancingServiceNameTaskIDDefault struct {
	_statusCode int

	Payload *models.GetIPLoadbalancingServiceNameTaskIDDefaultBody
}

// Code gets the status code for the get IP loadbalancing service name task ID default response
func (o *GetIPLoadbalancingServiceNameTaskIDDefault) Code() int {
	return o._statusCode
}

func (o *GetIPLoadbalancingServiceNameTaskIDDefault) Error() string {
	return fmt.Sprintf("[GET /ipLoadbalancing/{serviceName}/task/{id}][%d] GetIPLoadbalancingServiceNameTaskID default  %+v", o._statusCode, o.Payload)
}

func (o *GetIPLoadbalancingServiceNameTaskIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetIPLoadbalancingServiceNameTaskIDDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
