// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017 The go-ovh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetIPLoadbalancingServiceNameTCPFrontendParams creates a new GetIPLoadbalancingServiceNameTCPFrontendParams object
// with the default values initialized.
func NewGetIPLoadbalancingServiceNameTCPFrontendParams() *GetIPLoadbalancingServiceNameTCPFrontendParams {
	var ()
	return &GetIPLoadbalancingServiceNameTCPFrontendParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetIPLoadbalancingServiceNameTCPFrontendParamsWithTimeout creates a new GetIPLoadbalancingServiceNameTCPFrontendParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetIPLoadbalancingServiceNameTCPFrontendParamsWithTimeout(timeout time.Duration) *GetIPLoadbalancingServiceNameTCPFrontendParams {
	var ()
	return &GetIPLoadbalancingServiceNameTCPFrontendParams{

		timeout: timeout,
	}
}

// NewGetIPLoadbalancingServiceNameTCPFrontendParamsWithContext creates a new GetIPLoadbalancingServiceNameTCPFrontendParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetIPLoadbalancingServiceNameTCPFrontendParamsWithContext(ctx context.Context) *GetIPLoadbalancingServiceNameTCPFrontendParams {
	var ()
	return &GetIPLoadbalancingServiceNameTCPFrontendParams{

		Context: ctx,
	}
}

// NewGetIPLoadbalancingServiceNameTCPFrontendParamsWithHTTPClient creates a new GetIPLoadbalancingServiceNameTCPFrontendParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetIPLoadbalancingServiceNameTCPFrontendParamsWithHTTPClient(client *http.Client) *GetIPLoadbalancingServiceNameTCPFrontendParams {
	var ()
	return &GetIPLoadbalancingServiceNameTCPFrontendParams{
		HTTPClient: client,
	}
}

/*GetIPLoadbalancingServiceNameTCPFrontendParams contains all the parameters to send to the API endpoint
for the get IP loadbalancing service name TCP frontend operation typically these are written to a http.Request
*/
type GetIPLoadbalancingServiceNameTCPFrontendParams struct {

	/*DefaultFarmID*/
	DefaultFarmID *int64
	/*Port*/
	Port *string
	/*ServiceName*/
	ServiceName string
	/*Zone*/
	Zone *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get IP loadbalancing service name TCP frontend params
func (o *GetIPLoadbalancingServiceNameTCPFrontendParams) WithTimeout(timeout time.Duration) *GetIPLoadbalancingServiceNameTCPFrontendParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get IP loadbalancing service name TCP frontend params
func (o *GetIPLoadbalancingServiceNameTCPFrontendParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get IP loadbalancing service name TCP frontend params
func (o *GetIPLoadbalancingServiceNameTCPFrontendParams) WithContext(ctx context.Context) *GetIPLoadbalancingServiceNameTCPFrontendParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get IP loadbalancing service name TCP frontend params
func (o *GetIPLoadbalancingServiceNameTCPFrontendParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get IP loadbalancing service name TCP frontend params
func (o *GetIPLoadbalancingServiceNameTCPFrontendParams) WithHTTPClient(client *http.Client) *GetIPLoadbalancingServiceNameTCPFrontendParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get IP loadbalancing service name TCP frontend params
func (o *GetIPLoadbalancingServiceNameTCPFrontendParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDefaultFarmID adds the defaultFarmID to the get IP loadbalancing service name TCP frontend params
func (o *GetIPLoadbalancingServiceNameTCPFrontendParams) WithDefaultFarmID(defaultFarmID *int64) *GetIPLoadbalancingServiceNameTCPFrontendParams {
	o.SetDefaultFarmID(defaultFarmID)
	return o
}

// SetDefaultFarmID adds the defaultFarmId to the get IP loadbalancing service name TCP frontend params
func (o *GetIPLoadbalancingServiceNameTCPFrontendParams) SetDefaultFarmID(defaultFarmID *int64) {
	o.DefaultFarmID = defaultFarmID
}

// WithPort adds the port to the get IP loadbalancing service name TCP frontend params
func (o *GetIPLoadbalancingServiceNameTCPFrontendParams) WithPort(port *string) *GetIPLoadbalancingServiceNameTCPFrontendParams {
	o.SetPort(port)
	return o
}

// SetPort adds the port to the get IP loadbalancing service name TCP frontend params
func (o *GetIPLoadbalancingServiceNameTCPFrontendParams) SetPort(port *string) {
	o.Port = port
}

// WithServiceName adds the serviceName to the get IP loadbalancing service name TCP frontend params
func (o *GetIPLoadbalancingServiceNameTCPFrontendParams) WithServiceName(serviceName string) *GetIPLoadbalancingServiceNameTCPFrontendParams {
	o.SetServiceName(serviceName)
	return o
}

// SetServiceName adds the serviceName to the get IP loadbalancing service name TCP frontend params
func (o *GetIPLoadbalancingServiceNameTCPFrontendParams) SetServiceName(serviceName string) {
	o.ServiceName = serviceName
}

// WithZone adds the zone to the get IP loadbalancing service name TCP frontend params
func (o *GetIPLoadbalancingServiceNameTCPFrontendParams) WithZone(zone *string) *GetIPLoadbalancingServiceNameTCPFrontendParams {
	o.SetZone(zone)
	return o
}

// SetZone adds the zone to the get IP loadbalancing service name TCP frontend params
func (o *GetIPLoadbalancingServiceNameTCPFrontendParams) SetZone(zone *string) {
	o.Zone = zone
}

// WriteToRequest writes these params to a swagger request
func (o *GetIPLoadbalancingServiceNameTCPFrontendParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.DefaultFarmID != nil {

		// query param defaultFarmId
		var qrDefaultFarmID int64
		if o.DefaultFarmID != nil {
			qrDefaultFarmID = *o.DefaultFarmID
		}
		qDefaultFarmID := swag.FormatInt64(qrDefaultFarmID)
		if qDefaultFarmID != "" {
			if err := r.SetQueryParam("defaultFarmId", qDefaultFarmID); err != nil {
				return err
			}
		}

	}

	if o.Port != nil {

		// query param port
		var qrPort string
		if o.Port != nil {
			qrPort = *o.Port
		}
		qPort := qrPort
		if qPort != "" {
			if err := r.SetQueryParam("port", qPort); err != nil {
				return err
			}
		}

	}

	// path param serviceName
	if err := r.SetPathParam("serviceName", o.ServiceName); err != nil {
		return err
	}

	if o.Zone != nil {

		// query param zone
		var qrZone string
		if o.Zone != nil {
			qrZone = *o.Zone
		}
		qZone := qrZone
		if qZone != "" {
			if err := r.SetQueryParam("zone", qZone); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
