// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017 The go-ovh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/appscode/go-ovh/iploadbalancing/models"
)

// GetIPLoadbalancingServiceNameQuotaZoneReader is a Reader for the GetIPLoadbalancingServiceNameQuotaZone structure.
type GetIPLoadbalancingServiceNameQuotaZoneReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetIPLoadbalancingServiceNameQuotaZoneReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetIPLoadbalancingServiceNameQuotaZoneOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetIPLoadbalancingServiceNameQuotaZoneDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetIPLoadbalancingServiceNameQuotaZoneOK creates a GetIPLoadbalancingServiceNameQuotaZoneOK with default headers values
func NewGetIPLoadbalancingServiceNameQuotaZoneOK() *GetIPLoadbalancingServiceNameQuotaZoneOK {
	return &GetIPLoadbalancingServiceNameQuotaZoneOK{}
}

/*GetIPLoadbalancingServiceNameQuotaZoneOK handles this case with default header values.

description of 'iplb.Quota.Quota' response
*/
type GetIPLoadbalancingServiceNameQuotaZoneOK struct {
	Payload *models.IPLBQuotaQuota
}

func (o *GetIPLoadbalancingServiceNameQuotaZoneOK) Error() string {
	return fmt.Sprintf("[GET /ipLoadbalancing/{serviceName}/quota/{zone}][%d] getIpLoadbalancingServiceNameQuotaZoneOK  %+v", 200, o.Payload)
}

func (o *GetIPLoadbalancingServiceNameQuotaZoneOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IPLBQuotaQuota)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetIPLoadbalancingServiceNameQuotaZoneDefault creates a GetIPLoadbalancingServiceNameQuotaZoneDefault with default headers values
func NewGetIPLoadbalancingServiceNameQuotaZoneDefault(code int) *GetIPLoadbalancingServiceNameQuotaZoneDefault {
	return &GetIPLoadbalancingServiceNameQuotaZoneDefault{
		_statusCode: code,
	}
}

/*GetIPLoadbalancingServiceNameQuotaZoneDefault handles this case with default header values.

Unexpected error
*/
type GetIPLoadbalancingServiceNameQuotaZoneDefault struct {
	_statusCode int

	Payload *models.GetIPLoadbalancingServiceNameQuotaZoneDefaultBody
}

// Code gets the status code for the get IP loadbalancing service name quota zone default response
func (o *GetIPLoadbalancingServiceNameQuotaZoneDefault) Code() int {
	return o._statusCode
}

func (o *GetIPLoadbalancingServiceNameQuotaZoneDefault) Error() string {
	return fmt.Sprintf("[GET /ipLoadbalancing/{serviceName}/quota/{zone}][%d] GetIPLoadbalancingServiceNameQuotaZone default  %+v", o._statusCode, o.Payload)
}

func (o *GetIPLoadbalancingServiceNameQuotaZoneDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetIPLoadbalancingServiceNameQuotaZoneDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
