// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017 The go-ovh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/appscode/go-ovh/iploadbalancing/models"
)

// NewPostIPLoadbalancingServiceNameHTTPRouteParams creates a new PostIPLoadbalancingServiceNameHTTPRouteParams object
// with the default values initialized.
func NewPostIPLoadbalancingServiceNameHTTPRouteParams() *PostIPLoadbalancingServiceNameHTTPRouteParams {
	var ()
	return &PostIPLoadbalancingServiceNameHTTPRouteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostIPLoadbalancingServiceNameHTTPRouteParamsWithTimeout creates a new PostIPLoadbalancingServiceNameHTTPRouteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostIPLoadbalancingServiceNameHTTPRouteParamsWithTimeout(timeout time.Duration) *PostIPLoadbalancingServiceNameHTTPRouteParams {
	var ()
	return &PostIPLoadbalancingServiceNameHTTPRouteParams{

		timeout: timeout,
	}
}

// NewPostIPLoadbalancingServiceNameHTTPRouteParamsWithContext creates a new PostIPLoadbalancingServiceNameHTTPRouteParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostIPLoadbalancingServiceNameHTTPRouteParamsWithContext(ctx context.Context) *PostIPLoadbalancingServiceNameHTTPRouteParams {
	var ()
	return &PostIPLoadbalancingServiceNameHTTPRouteParams{

		Context: ctx,
	}
}

// NewPostIPLoadbalancingServiceNameHTTPRouteParamsWithHTTPClient creates a new PostIPLoadbalancingServiceNameHTTPRouteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostIPLoadbalancingServiceNameHTTPRouteParamsWithHTTPClient(client *http.Client) *PostIPLoadbalancingServiceNameHTTPRouteParams {
	var ()
	return &PostIPLoadbalancingServiceNameHTTPRouteParams{
		HTTPClient: client,
	}
}

/*PostIPLoadbalancingServiceNameHTTPRouteParams contains all the parameters to send to the API endpoint
for the post IP loadbalancing service name HTTP route operation typically these are written to a http.Request
*/
type PostIPLoadbalancingServiceNameHTTPRouteParams struct {

	/*IPLBHTTPRoutePost*/
	IPLBHTTPRoutePost *models.PostIPLoadbalancingServiceNameHTTPRouteParamsBody
	/*ServiceName*/
	ServiceName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post IP loadbalancing service name HTTP route params
func (o *PostIPLoadbalancingServiceNameHTTPRouteParams) WithTimeout(timeout time.Duration) *PostIPLoadbalancingServiceNameHTTPRouteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post IP loadbalancing service name HTTP route params
func (o *PostIPLoadbalancingServiceNameHTTPRouteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post IP loadbalancing service name HTTP route params
func (o *PostIPLoadbalancingServiceNameHTTPRouteParams) WithContext(ctx context.Context) *PostIPLoadbalancingServiceNameHTTPRouteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post IP loadbalancing service name HTTP route params
func (o *PostIPLoadbalancingServiceNameHTTPRouteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post IP loadbalancing service name HTTP route params
func (o *PostIPLoadbalancingServiceNameHTTPRouteParams) WithHTTPClient(client *http.Client) *PostIPLoadbalancingServiceNameHTTPRouteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post IP loadbalancing service name HTTP route params
func (o *PostIPLoadbalancingServiceNameHTTPRouteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIPLBHTTPRoutePost adds the iPLBHTTPRoutePost to the post IP loadbalancing service name HTTP route params
func (o *PostIPLoadbalancingServiceNameHTTPRouteParams) WithIPLBHTTPRoutePost(iPLBHTTPRoutePost *models.PostIPLoadbalancingServiceNameHTTPRouteParamsBody) *PostIPLoadbalancingServiceNameHTTPRouteParams {
	o.SetIPLBHTTPRoutePost(iPLBHTTPRoutePost)
	return o
}

// SetIPLBHTTPRoutePost adds the iplbHttpRoutePost to the post IP loadbalancing service name HTTP route params
func (o *PostIPLoadbalancingServiceNameHTTPRouteParams) SetIPLBHTTPRoutePost(iPLBHTTPRoutePost *models.PostIPLoadbalancingServiceNameHTTPRouteParamsBody) {
	o.IPLBHTTPRoutePost = iPLBHTTPRoutePost
}

// WithServiceName adds the serviceName to the post IP loadbalancing service name HTTP route params
func (o *PostIPLoadbalancingServiceNameHTTPRouteParams) WithServiceName(serviceName string) *PostIPLoadbalancingServiceNameHTTPRouteParams {
	o.SetServiceName(serviceName)
	return o
}

// SetServiceName adds the serviceName to the post IP loadbalancing service name HTTP route params
func (o *PostIPLoadbalancingServiceNameHTTPRouteParams) SetServiceName(serviceName string) {
	o.ServiceName = serviceName
}

// WriteToRequest writes these params to a swagger request
func (o *PostIPLoadbalancingServiceNameHTTPRouteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.IPLBHTTPRoutePost != nil {
		if err := r.SetBodyParam(o.IPLBHTTPRoutePost); err != nil {
			return err
		}
	}

	// path param serviceName
	if err := r.SetPathParam("serviceName", o.ServiceName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
