// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017 The go-ovh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetVrackServiceNameCloudProjectProjectParams creates a new GetVrackServiceNameCloudProjectProjectParams object
// with the default values initialized.
func NewGetVrackServiceNameCloudProjectProjectParams() *GetVrackServiceNameCloudProjectProjectParams {
	var ()
	return &GetVrackServiceNameCloudProjectProjectParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetVrackServiceNameCloudProjectProjectParamsWithTimeout creates a new GetVrackServiceNameCloudProjectProjectParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetVrackServiceNameCloudProjectProjectParamsWithTimeout(timeout time.Duration) *GetVrackServiceNameCloudProjectProjectParams {
	var ()
	return &GetVrackServiceNameCloudProjectProjectParams{

		timeout: timeout,
	}
}

// NewGetVrackServiceNameCloudProjectProjectParamsWithContext creates a new GetVrackServiceNameCloudProjectProjectParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetVrackServiceNameCloudProjectProjectParamsWithContext(ctx context.Context) *GetVrackServiceNameCloudProjectProjectParams {
	var ()
	return &GetVrackServiceNameCloudProjectProjectParams{

		Context: ctx,
	}
}

// NewGetVrackServiceNameCloudProjectProjectParamsWithHTTPClient creates a new GetVrackServiceNameCloudProjectProjectParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetVrackServiceNameCloudProjectProjectParamsWithHTTPClient(client *http.Client) *GetVrackServiceNameCloudProjectProjectParams {
	var ()
	return &GetVrackServiceNameCloudProjectProjectParams{
		HTTPClient: client,
	}
}

/*GetVrackServiceNameCloudProjectProjectParams contains all the parameters to send to the API endpoint
for the get vrack service name cloud project project operation typically these are written to a http.Request
*/
type GetVrackServiceNameCloudProjectProjectParams struct {

	/*Project*/
	Project string
	/*ServiceName*/
	ServiceName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get vrack service name cloud project project params
func (o *GetVrackServiceNameCloudProjectProjectParams) WithTimeout(timeout time.Duration) *GetVrackServiceNameCloudProjectProjectParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get vrack service name cloud project project params
func (o *GetVrackServiceNameCloudProjectProjectParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get vrack service name cloud project project params
func (o *GetVrackServiceNameCloudProjectProjectParams) WithContext(ctx context.Context) *GetVrackServiceNameCloudProjectProjectParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get vrack service name cloud project project params
func (o *GetVrackServiceNameCloudProjectProjectParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get vrack service name cloud project project params
func (o *GetVrackServiceNameCloudProjectProjectParams) WithHTTPClient(client *http.Client) *GetVrackServiceNameCloudProjectProjectParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get vrack service name cloud project project params
func (o *GetVrackServiceNameCloudProjectProjectParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProject adds the project to the get vrack service name cloud project project params
func (o *GetVrackServiceNameCloudProjectProjectParams) WithProject(project string) *GetVrackServiceNameCloudProjectProjectParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the get vrack service name cloud project project params
func (o *GetVrackServiceNameCloudProjectProjectParams) SetProject(project string) {
	o.Project = project
}

// WithServiceName adds the serviceName to the get vrack service name cloud project project params
func (o *GetVrackServiceNameCloudProjectProjectParams) WithServiceName(serviceName string) *GetVrackServiceNameCloudProjectProjectParams {
	o.SetServiceName(serviceName)
	return o
}

// SetServiceName adds the serviceName to the get vrack service name cloud project project params
func (o *GetVrackServiceNameCloudProjectProjectParams) SetServiceName(serviceName string) {
	o.ServiceName = serviceName
}

// WriteToRequest writes these params to a swagger request
func (o *GetVrackServiceNameCloudProjectProjectParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	// path param serviceName
	if err := r.SetPathParam("serviceName", o.ServiceName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
