// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017 The go-ovh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/appscode/go-ovh/vrack/models"
)

// GetVrackServiceNameAllowedServicesReader is a Reader for the GetVrackServiceNameAllowedServices structure.
type GetVrackServiceNameAllowedServicesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetVrackServiceNameAllowedServicesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetVrackServiceNameAllowedServicesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetVrackServiceNameAllowedServicesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetVrackServiceNameAllowedServicesOK creates a GetVrackServiceNameAllowedServicesOK with default headers values
func NewGetVrackServiceNameAllowedServicesOK() *GetVrackServiceNameAllowedServicesOK {
	return &GetVrackServiceNameAllowedServicesOK{}
}

/*GetVrackServiceNameAllowedServicesOK handles this case with default header values.

description of 'vrack.AllowedServices' response
*/
type GetVrackServiceNameAllowedServicesOK struct {
	Payload *models.VrackAllowedServices
}

func (o *GetVrackServiceNameAllowedServicesOK) Error() string {
	return fmt.Sprintf("[GET /vrack/{serviceName}/allowedServices][%d] getVrackServiceNameAllowedServicesOK  %+v", 200, o.Payload)
}

func (o *GetVrackServiceNameAllowedServicesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.VrackAllowedServices)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetVrackServiceNameAllowedServicesDefault creates a GetVrackServiceNameAllowedServicesDefault with default headers values
func NewGetVrackServiceNameAllowedServicesDefault(code int) *GetVrackServiceNameAllowedServicesDefault {
	return &GetVrackServiceNameAllowedServicesDefault{
		_statusCode: code,
	}
}

/*GetVrackServiceNameAllowedServicesDefault handles this case with default header values.

Unexpected error
*/
type GetVrackServiceNameAllowedServicesDefault struct {
	_statusCode int

	Payload *models.GetVrackServiceNameAllowedServicesDefaultBody
}

// Code gets the status code for the get vrack service name allowed services default response
func (o *GetVrackServiceNameAllowedServicesDefault) Code() int {
	return o._statusCode
}

func (o *GetVrackServiceNameAllowedServicesDefault) Error() string {
	return fmt.Sprintf("[GET /vrack/{serviceName}/allowedServices][%d] GetVrackServiceNameAllowedServices default  %+v", o._statusCode, o.Payload)
}

func (o *GetVrackServiceNameAllowedServicesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetVrackServiceNameAllowedServicesDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
