// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017 The go-ovh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/appscode/go-ovh/vrack/models"
)

// NewPostVrackServiceNameCloudProjectParams creates a new PostVrackServiceNameCloudProjectParams object
// with the default values initialized.
func NewPostVrackServiceNameCloudProjectParams() *PostVrackServiceNameCloudProjectParams {
	var ()
	return &PostVrackServiceNameCloudProjectParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostVrackServiceNameCloudProjectParamsWithTimeout creates a new PostVrackServiceNameCloudProjectParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostVrackServiceNameCloudProjectParamsWithTimeout(timeout time.Duration) *PostVrackServiceNameCloudProjectParams {
	var ()
	return &PostVrackServiceNameCloudProjectParams{

		timeout: timeout,
	}
}

// NewPostVrackServiceNameCloudProjectParamsWithContext creates a new PostVrackServiceNameCloudProjectParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostVrackServiceNameCloudProjectParamsWithContext(ctx context.Context) *PostVrackServiceNameCloudProjectParams {
	var ()
	return &PostVrackServiceNameCloudProjectParams{

		Context: ctx,
	}
}

// NewPostVrackServiceNameCloudProjectParamsWithHTTPClient creates a new PostVrackServiceNameCloudProjectParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostVrackServiceNameCloudProjectParamsWithHTTPClient(client *http.Client) *PostVrackServiceNameCloudProjectParams {
	var ()
	return &PostVrackServiceNameCloudProjectParams{
		HTTPClient: client,
	}
}

/*PostVrackServiceNameCloudProjectParams contains all the parameters to send to the API endpoint
for the post vrack service name cloud project operation typically these are written to a http.Request
*/
type PostVrackServiceNameCloudProjectParams struct {

	/*ServiceName*/
	ServiceName string
	/*VrackCloudProjectPost*/
	VrackCloudProjectPost *models.PostVrackServiceNameCloudProjectParamsBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post vrack service name cloud project params
func (o *PostVrackServiceNameCloudProjectParams) WithTimeout(timeout time.Duration) *PostVrackServiceNameCloudProjectParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post vrack service name cloud project params
func (o *PostVrackServiceNameCloudProjectParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post vrack service name cloud project params
func (o *PostVrackServiceNameCloudProjectParams) WithContext(ctx context.Context) *PostVrackServiceNameCloudProjectParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post vrack service name cloud project params
func (o *PostVrackServiceNameCloudProjectParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post vrack service name cloud project params
func (o *PostVrackServiceNameCloudProjectParams) WithHTTPClient(client *http.Client) *PostVrackServiceNameCloudProjectParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post vrack service name cloud project params
func (o *PostVrackServiceNameCloudProjectParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithServiceName adds the serviceName to the post vrack service name cloud project params
func (o *PostVrackServiceNameCloudProjectParams) WithServiceName(serviceName string) *PostVrackServiceNameCloudProjectParams {
	o.SetServiceName(serviceName)
	return o
}

// SetServiceName adds the serviceName to the post vrack service name cloud project params
func (o *PostVrackServiceNameCloudProjectParams) SetServiceName(serviceName string) {
	o.ServiceName = serviceName
}

// WithVrackCloudProjectPost adds the vrackCloudProjectPost to the post vrack service name cloud project params
func (o *PostVrackServiceNameCloudProjectParams) WithVrackCloudProjectPost(vrackCloudProjectPost *models.PostVrackServiceNameCloudProjectParamsBody) *PostVrackServiceNameCloudProjectParams {
	o.SetVrackCloudProjectPost(vrackCloudProjectPost)
	return o
}

// SetVrackCloudProjectPost adds the vrackCloudProjectPost to the post vrack service name cloud project params
func (o *PostVrackServiceNameCloudProjectParams) SetVrackCloudProjectPost(vrackCloudProjectPost *models.PostVrackServiceNameCloudProjectParamsBody) {
	o.VrackCloudProjectPost = vrackCloudProjectPost
}

// WriteToRequest writes these params to a swagger request
func (o *PostVrackServiceNameCloudProjectParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param serviceName
	if err := r.SetPathParam("serviceName", o.ServiceName); err != nil {
		return err
	}

	if o.VrackCloudProjectPost != nil {
		if err := r.SetBodyParam(o.VrackCloudProjectPost); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
