// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017 The go-ovh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ComplexTypeUnitAndValuesVpsVpsTimestampValue A value set tagged with its unit
// swagger:model complexType.UnitAndValues.Vps.VpsTimestampValue
type ComplexTypeUnitAndValuesVpsVpsTimestampValue struct {

	// unit
	Unit string `json:"unit,omitempty"`

	// values
	Values ComplexTypeUnitAndValuesVpsVpsTimestampValueValues `json:"values"`
}

// Validate validates this complex type unit and values vps vps timestamp value
func (m *ComplexTypeUnitAndValuesVpsVpsTimestampValue) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ComplexTypeUnitAndValuesVpsVpsTimestampValue) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ComplexTypeUnitAndValuesVpsVpsTimestampValue) UnmarshalBinary(b []byte) error {
	var res ComplexTypeUnitAndValuesVpsVpsTimestampValue
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
