// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017 The go-ovh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// IPLBBackendUDPCustomerServerBackendUDPServer UDP Farm's Server
// swagger:model iplb.BackendUdpCustomerServer.BackendUDPServer
type IPLBBackendUDPCustomerServerBackendUDPServer struct {

	// Address of your server
	// Required: true
	// Read Only: true
	Address string `json:"address"`

	// farm id
	// Required: true
	// Read Only: true
	BackendID int64 `json:"backendId"`

	// Human readable name for your server, this field is for you
	DisplayName string `json:"displayName,omitempty"`

	// Port attached to your server. Inherited from farm if null
	Port int64 `json:"port,omitempty"`

	// Id of your server
	// Required: true
	// Read Only: true
	ServerID int64 `json:"serverId"`

	// Status attached to your server
	Status string `json:"status,omitempty"`
}

// Validate validates this iplb backend Udp customer server backend UDP server
func (m *IPLBBackendUDPCustomerServerBackendUDPServer) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAddress(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateBackendID(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateServerID(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IPLBBackendUDPCustomerServerBackendUDPServer) validateAddress(formats strfmt.Registry) error {

	if err := validate.RequiredString("address", "body", string(m.Address)); err != nil {
		return err
	}

	return nil
}

func (m *IPLBBackendUDPCustomerServerBackendUDPServer) validateBackendID(formats strfmt.Registry) error {

	if err := validate.Required("backendId", "body", int64(m.BackendID)); err != nil {
		return err
	}

	return nil
}

func (m *IPLBBackendUDPCustomerServerBackendUDPServer) validateServerID(formats strfmt.Registry) error {

	if err := validate.Required("serverId", "body", int64(m.ServerID)); err != nil {
		return err
	}

	return nil
}

var iplbBackendUdpCustomerServerBackendUdpServerTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["active","inactive"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		iplbBackendUdpCustomerServerBackendUdpServerTypeStatusPropEnum = append(iplbBackendUdpCustomerServerBackendUdpServerTypeStatusPropEnum, v)
	}
}

const (
	// IPLBBackendUDPCustomerServerBackendUDPServerStatusActive captures enum value "active"
	IPLBBackendUDPCustomerServerBackendUDPServerStatusActive string = "active"
	// IPLBBackendUDPCustomerServerBackendUDPServerStatusInactive captures enum value "inactive"
	IPLBBackendUDPCustomerServerBackendUDPServerStatusInactive string = "inactive"
)

// prop value enum
func (m *IPLBBackendUDPCustomerServerBackendUDPServer) validateStatusEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, iplbBackendUdpCustomerServerBackendUdpServerTypeStatusPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *IPLBBackendUDPCustomerServerBackendUDPServer) validateStatus(formats strfmt.Registry) error {

	if swag.IsZero(m.Status) { // not required
		return nil
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", m.Status); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *IPLBBackendUDPCustomerServerBackendUDPServer) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IPLBBackendUDPCustomerServerBackendUDPServer) UnmarshalBinary(b []byte) error {
	var res IPLBBackendUDPCustomerServerBackendUDPServer
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
