// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017 The go-ovh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetVpsServiceNameDisksIDMonitoringParams creates a new GetVpsServiceNameDisksIDMonitoringParams object
// with the default values initialized.
func NewGetVpsServiceNameDisksIDMonitoringParams() *GetVpsServiceNameDisksIDMonitoringParams {
	var ()
	return &GetVpsServiceNameDisksIDMonitoringParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetVpsServiceNameDisksIDMonitoringParamsWithTimeout creates a new GetVpsServiceNameDisksIDMonitoringParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetVpsServiceNameDisksIDMonitoringParamsWithTimeout(timeout time.Duration) *GetVpsServiceNameDisksIDMonitoringParams {
	var ()
	return &GetVpsServiceNameDisksIDMonitoringParams{

		timeout: timeout,
	}
}

// NewGetVpsServiceNameDisksIDMonitoringParamsWithContext creates a new GetVpsServiceNameDisksIDMonitoringParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetVpsServiceNameDisksIDMonitoringParamsWithContext(ctx context.Context) *GetVpsServiceNameDisksIDMonitoringParams {
	var ()
	return &GetVpsServiceNameDisksIDMonitoringParams{

		Context: ctx,
	}
}

// NewGetVpsServiceNameDisksIDMonitoringParamsWithHTTPClient creates a new GetVpsServiceNameDisksIDMonitoringParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetVpsServiceNameDisksIDMonitoringParamsWithHTTPClient(client *http.Client) *GetVpsServiceNameDisksIDMonitoringParams {
	var ()
	return &GetVpsServiceNameDisksIDMonitoringParams{
		HTTPClient: client,
	}
}

/*GetVpsServiceNameDisksIDMonitoringParams contains all the parameters to send to the API endpoint
for the get vps service name disks ID monitoring operation typically these are written to a http.Request
*/
type GetVpsServiceNameDisksIDMonitoringParams struct {

	/*ID*/
	ID int64
	/*Period*/
	Period string
	/*ServiceName*/
	ServiceName string
	/*Type*/
	Type string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get vps service name disks ID monitoring params
func (o *GetVpsServiceNameDisksIDMonitoringParams) WithTimeout(timeout time.Duration) *GetVpsServiceNameDisksIDMonitoringParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get vps service name disks ID monitoring params
func (o *GetVpsServiceNameDisksIDMonitoringParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get vps service name disks ID monitoring params
func (o *GetVpsServiceNameDisksIDMonitoringParams) WithContext(ctx context.Context) *GetVpsServiceNameDisksIDMonitoringParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get vps service name disks ID monitoring params
func (o *GetVpsServiceNameDisksIDMonitoringParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get vps service name disks ID monitoring params
func (o *GetVpsServiceNameDisksIDMonitoringParams) WithHTTPClient(client *http.Client) *GetVpsServiceNameDisksIDMonitoringParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get vps service name disks ID monitoring params
func (o *GetVpsServiceNameDisksIDMonitoringParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get vps service name disks ID monitoring params
func (o *GetVpsServiceNameDisksIDMonitoringParams) WithID(id int64) *GetVpsServiceNameDisksIDMonitoringParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get vps service name disks ID monitoring params
func (o *GetVpsServiceNameDisksIDMonitoringParams) SetID(id int64) {
	o.ID = id
}

// WithPeriod adds the period to the get vps service name disks ID monitoring params
func (o *GetVpsServiceNameDisksIDMonitoringParams) WithPeriod(period string) *GetVpsServiceNameDisksIDMonitoringParams {
	o.SetPeriod(period)
	return o
}

// SetPeriod adds the period to the get vps service name disks ID monitoring params
func (o *GetVpsServiceNameDisksIDMonitoringParams) SetPeriod(period string) {
	o.Period = period
}

// WithServiceName adds the serviceName to the get vps service name disks ID monitoring params
func (o *GetVpsServiceNameDisksIDMonitoringParams) WithServiceName(serviceName string) *GetVpsServiceNameDisksIDMonitoringParams {
	o.SetServiceName(serviceName)
	return o
}

// SetServiceName adds the serviceName to the get vps service name disks ID monitoring params
func (o *GetVpsServiceNameDisksIDMonitoringParams) SetServiceName(serviceName string) {
	o.ServiceName = serviceName
}

// WithType adds the typeVar to the get vps service name disks ID monitoring params
func (o *GetVpsServiceNameDisksIDMonitoringParams) WithType(typeVar string) *GetVpsServiceNameDisksIDMonitoringParams {
	o.SetType(typeVar)
	return o
}

// SetType adds the type to the get vps service name disks ID monitoring params
func (o *GetVpsServiceNameDisksIDMonitoringParams) SetType(typeVar string) {
	o.Type = typeVar
}

// WriteToRequest writes these params to a swagger request
func (o *GetVpsServiceNameDisksIDMonitoringParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	// query param period
	qrPeriod := o.Period
	qPeriod := qrPeriod
	if qPeriod != "" {
		if err := r.SetQueryParam("period", qPeriod); err != nil {
			return err
		}
	}

	// path param serviceName
	if err := r.SetPathParam("serviceName", o.ServiceName); err != nil {
		return err
	}

	// query param type
	qrType := o.Type
	qType := qrType
	if qType != "" {
		if err := r.SetQueryParam("type", qType); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
