// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017 The go-ovh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/appscode/go-ovh/vps/models"
)

// GetVpsServiceNameDisksReader is a Reader for the GetVpsServiceNameDisks structure.
type GetVpsServiceNameDisksReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetVpsServiceNameDisksReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetVpsServiceNameDisksOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetVpsServiceNameDisksDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetVpsServiceNameDisksOK creates a GetVpsServiceNameDisksOK with default headers values
func NewGetVpsServiceNameDisksOK() *GetVpsServiceNameDisksOK {
	return &GetVpsServiceNameDisksOK{}
}

/*GetVpsServiceNameDisksOK handles this case with default header values.

return value
*/
type GetVpsServiceNameDisksOK struct {
	Payload []int64
}

func (o *GetVpsServiceNameDisksOK) Error() string {
	return fmt.Sprintf("[GET /vps/{serviceName}/disks][%d] getVpsServiceNameDisksOK  %+v", 200, o.Payload)
}

func (o *GetVpsServiceNameDisksOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetVpsServiceNameDisksDefault creates a GetVpsServiceNameDisksDefault with default headers values
func NewGetVpsServiceNameDisksDefault(code int) *GetVpsServiceNameDisksDefault {
	return &GetVpsServiceNameDisksDefault{
		_statusCode: code,
	}
}

/*GetVpsServiceNameDisksDefault handles this case with default header values.

Unexpected error
*/
type GetVpsServiceNameDisksDefault struct {
	_statusCode int

	Payload *models.GetVpsServiceNameDisksDefaultBody
}

// Code gets the status code for the get vps service name disks default response
func (o *GetVpsServiceNameDisksDefault) Code() int {
	return o._statusCode
}

func (o *GetVpsServiceNameDisksDefault) Error() string {
	return fmt.Sprintf("[GET /vps/{serviceName}/disks][%d] GetVpsServiceNameDisks default  %+v", o._statusCode, o.Payload)
}

func (o *GetVpsServiceNameDisksDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetVpsServiceNameDisksDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
