// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017 The go-ovh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteIPIPDelegationTargetParams creates a new DeleteIPIPDelegationTargetParams object
// with the default values initialized.
func NewDeleteIPIPDelegationTargetParams() *DeleteIPIPDelegationTargetParams {
	var ()
	return &DeleteIPIPDelegationTargetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteIPIPDelegationTargetParamsWithTimeout creates a new DeleteIPIPDelegationTargetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteIPIPDelegationTargetParamsWithTimeout(timeout time.Duration) *DeleteIPIPDelegationTargetParams {
	var ()
	return &DeleteIPIPDelegationTargetParams{

		timeout: timeout,
	}
}

// NewDeleteIPIPDelegationTargetParamsWithContext creates a new DeleteIPIPDelegationTargetParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteIPIPDelegationTargetParamsWithContext(ctx context.Context) *DeleteIPIPDelegationTargetParams {
	var ()
	return &DeleteIPIPDelegationTargetParams{

		Context: ctx,
	}
}

// NewDeleteIPIPDelegationTargetParamsWithHTTPClient creates a new DeleteIPIPDelegationTargetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteIPIPDelegationTargetParamsWithHTTPClient(client *http.Client) *DeleteIPIPDelegationTargetParams {
	var ()
	return &DeleteIPIPDelegationTargetParams{
		HTTPClient: client,
	}
}

/*DeleteIPIPDelegationTargetParams contains all the parameters to send to the API endpoint
for the delete IP IP delegation target operation typically these are written to a http.Request
*/
type DeleteIPIPDelegationTargetParams struct {

	/*IP*/
	IP string
	/*Target*/
	Target string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete IP IP delegation target params
func (o *DeleteIPIPDelegationTargetParams) WithTimeout(timeout time.Duration) *DeleteIPIPDelegationTargetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete IP IP delegation target params
func (o *DeleteIPIPDelegationTargetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete IP IP delegation target params
func (o *DeleteIPIPDelegationTargetParams) WithContext(ctx context.Context) *DeleteIPIPDelegationTargetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete IP IP delegation target params
func (o *DeleteIPIPDelegationTargetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete IP IP delegation target params
func (o *DeleteIPIPDelegationTargetParams) WithHTTPClient(client *http.Client) *DeleteIPIPDelegationTargetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete IP IP delegation target params
func (o *DeleteIPIPDelegationTargetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIP adds the ip to the delete IP IP delegation target params
func (o *DeleteIPIPDelegationTargetParams) WithIP(ip string) *DeleteIPIPDelegationTargetParams {
	o.SetIP(ip)
	return o
}

// SetIP adds the ip to the delete IP IP delegation target params
func (o *DeleteIPIPDelegationTargetParams) SetIP(ip string) {
	o.IP = ip
}

// WithTarget adds the target to the delete IP IP delegation target params
func (o *DeleteIPIPDelegationTargetParams) WithTarget(target string) *DeleteIPIPDelegationTargetParams {
	o.SetTarget(target)
	return o
}

// SetTarget adds the target to the delete IP IP delegation target params
func (o *DeleteIPIPDelegationTargetParams) SetTarget(target string) {
	o.Target = target
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteIPIPDelegationTargetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param ip
	if err := r.SetPathParam("ip", o.IP); err != nil {
		return err
	}

	// path param target
	if err := r.SetPathParam("target", o.Target); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
