// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017 The go-ovh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetIPIPFirewallIPOnFirewallRuleSequenceParams creates a new GetIPIPFirewallIPOnFirewallRuleSequenceParams object
// with the default values initialized.
func NewGetIPIPFirewallIPOnFirewallRuleSequenceParams() *GetIPIPFirewallIPOnFirewallRuleSequenceParams {
	var ()
	return &GetIPIPFirewallIPOnFirewallRuleSequenceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetIPIPFirewallIPOnFirewallRuleSequenceParamsWithTimeout creates a new GetIPIPFirewallIPOnFirewallRuleSequenceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetIPIPFirewallIPOnFirewallRuleSequenceParamsWithTimeout(timeout time.Duration) *GetIPIPFirewallIPOnFirewallRuleSequenceParams {
	var ()
	return &GetIPIPFirewallIPOnFirewallRuleSequenceParams{

		timeout: timeout,
	}
}

// NewGetIPIPFirewallIPOnFirewallRuleSequenceParamsWithContext creates a new GetIPIPFirewallIPOnFirewallRuleSequenceParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetIPIPFirewallIPOnFirewallRuleSequenceParamsWithContext(ctx context.Context) *GetIPIPFirewallIPOnFirewallRuleSequenceParams {
	var ()
	return &GetIPIPFirewallIPOnFirewallRuleSequenceParams{

		Context: ctx,
	}
}

// NewGetIPIPFirewallIPOnFirewallRuleSequenceParamsWithHTTPClient creates a new GetIPIPFirewallIPOnFirewallRuleSequenceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetIPIPFirewallIPOnFirewallRuleSequenceParamsWithHTTPClient(client *http.Client) *GetIPIPFirewallIPOnFirewallRuleSequenceParams {
	var ()
	return &GetIPIPFirewallIPOnFirewallRuleSequenceParams{
		HTTPClient: client,
	}
}

/*GetIPIPFirewallIPOnFirewallRuleSequenceParams contains all the parameters to send to the API endpoint
for the get IP IP firewall IP on firewall rule sequence operation typically these are written to a http.Request
*/
type GetIPIPFirewallIPOnFirewallRuleSequenceParams struct {

	/*IP*/
	IP string
	/*IPOnFirewall*/
	IPOnFirewall string
	/*Sequence*/
	Sequence int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get IP IP firewall IP on firewall rule sequence params
func (o *GetIPIPFirewallIPOnFirewallRuleSequenceParams) WithTimeout(timeout time.Duration) *GetIPIPFirewallIPOnFirewallRuleSequenceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get IP IP firewall IP on firewall rule sequence params
func (o *GetIPIPFirewallIPOnFirewallRuleSequenceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get IP IP firewall IP on firewall rule sequence params
func (o *GetIPIPFirewallIPOnFirewallRuleSequenceParams) WithContext(ctx context.Context) *GetIPIPFirewallIPOnFirewallRuleSequenceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get IP IP firewall IP on firewall rule sequence params
func (o *GetIPIPFirewallIPOnFirewallRuleSequenceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get IP IP firewall IP on firewall rule sequence params
func (o *GetIPIPFirewallIPOnFirewallRuleSequenceParams) WithHTTPClient(client *http.Client) *GetIPIPFirewallIPOnFirewallRuleSequenceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get IP IP firewall IP on firewall rule sequence params
func (o *GetIPIPFirewallIPOnFirewallRuleSequenceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIP adds the ip to the get IP IP firewall IP on firewall rule sequence params
func (o *GetIPIPFirewallIPOnFirewallRuleSequenceParams) WithIP(ip string) *GetIPIPFirewallIPOnFirewallRuleSequenceParams {
	o.SetIP(ip)
	return o
}

// SetIP adds the ip to the get IP IP firewall IP on firewall rule sequence params
func (o *GetIPIPFirewallIPOnFirewallRuleSequenceParams) SetIP(ip string) {
	o.IP = ip
}

// WithIPOnFirewall adds the iPOnFirewall to the get IP IP firewall IP on firewall rule sequence params
func (o *GetIPIPFirewallIPOnFirewallRuleSequenceParams) WithIPOnFirewall(iPOnFirewall string) *GetIPIPFirewallIPOnFirewallRuleSequenceParams {
	o.SetIPOnFirewall(iPOnFirewall)
	return o
}

// SetIPOnFirewall adds the ipOnFirewall to the get IP IP firewall IP on firewall rule sequence params
func (o *GetIPIPFirewallIPOnFirewallRuleSequenceParams) SetIPOnFirewall(iPOnFirewall string) {
	o.IPOnFirewall = iPOnFirewall
}

// WithSequence adds the sequence to the get IP IP firewall IP on firewall rule sequence params
func (o *GetIPIPFirewallIPOnFirewallRuleSequenceParams) WithSequence(sequence int64) *GetIPIPFirewallIPOnFirewallRuleSequenceParams {
	o.SetSequence(sequence)
	return o
}

// SetSequence adds the sequence to the get IP IP firewall IP on firewall rule sequence params
func (o *GetIPIPFirewallIPOnFirewallRuleSequenceParams) SetSequence(sequence int64) {
	o.Sequence = sequence
}

// WriteToRequest writes these params to a swagger request
func (o *GetIPIPFirewallIPOnFirewallRuleSequenceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param ip
	if err := r.SetPathParam("ip", o.IP); err != nil {
		return err
	}

	// path param ipOnFirewall
	if err := r.SetPathParam("ipOnFirewall", o.IPOnFirewall); err != nil {
		return err
	}

	// path param sequence
	if err := r.SetPathParam("sequence", swag.FormatInt64(o.Sequence)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
