// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017 The go-ovh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetIPIPPhishingIDParams creates a new GetIPIPPhishingIDParams object
// with the default values initialized.
func NewGetIPIPPhishingIDParams() *GetIPIPPhishingIDParams {
	var ()
	return &GetIPIPPhishingIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetIPIPPhishingIDParamsWithTimeout creates a new GetIPIPPhishingIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetIPIPPhishingIDParamsWithTimeout(timeout time.Duration) *GetIPIPPhishingIDParams {
	var ()
	return &GetIPIPPhishingIDParams{

		timeout: timeout,
	}
}

// NewGetIPIPPhishingIDParamsWithContext creates a new GetIPIPPhishingIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetIPIPPhishingIDParamsWithContext(ctx context.Context) *GetIPIPPhishingIDParams {
	var ()
	return &GetIPIPPhishingIDParams{

		Context: ctx,
	}
}

// NewGetIPIPPhishingIDParamsWithHTTPClient creates a new GetIPIPPhishingIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetIPIPPhishingIDParamsWithHTTPClient(client *http.Client) *GetIPIPPhishingIDParams {
	var ()
	return &GetIPIPPhishingIDParams{
		HTTPClient: client,
	}
}

/*GetIPIPPhishingIDParams contains all the parameters to send to the API endpoint
for the get IP IP phishing ID operation typically these are written to a http.Request
*/
type GetIPIPPhishingIDParams struct {

	/*ID*/
	ID int64
	/*IP*/
	IP string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get IP IP phishing ID params
func (o *GetIPIPPhishingIDParams) WithTimeout(timeout time.Duration) *GetIPIPPhishingIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get IP IP phishing ID params
func (o *GetIPIPPhishingIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get IP IP phishing ID params
func (o *GetIPIPPhishingIDParams) WithContext(ctx context.Context) *GetIPIPPhishingIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get IP IP phishing ID params
func (o *GetIPIPPhishingIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get IP IP phishing ID params
func (o *GetIPIPPhishingIDParams) WithHTTPClient(client *http.Client) *GetIPIPPhishingIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get IP IP phishing ID params
func (o *GetIPIPPhishingIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get IP IP phishing ID params
func (o *GetIPIPPhishingIDParams) WithID(id int64) *GetIPIPPhishingIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get IP IP phishing ID params
func (o *GetIPIPPhishingIDParams) SetID(id int64) {
	o.ID = id
}

// WithIP adds the ip to the get IP IP phishing ID params
func (o *GetIPIPPhishingIDParams) WithIP(ip string) *GetIPIPPhishingIDParams {
	o.SetIP(ip)
	return o
}

// SetIP adds the ip to the get IP IP phishing ID params
func (o *GetIPIPPhishingIDParams) SetIP(ip string) {
	o.IP = ip
}

// WriteToRequest writes these params to a swagger request
func (o *GetIPIPPhishingIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	// path param ip
	if err := r.SetPathParam("ip", o.IP); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
