// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017 The go-ovh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/appscode/go-ovh/domain/models"
)

// DeleteDomainDataSmdSmdIDReader is a Reader for the DeleteDomainDataSmdSmdID structure.
type DeleteDomainDataSmdSmdIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteDomainDataSmdSmdIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteDomainDataSmdSmdIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewDeleteDomainDataSmdSmdIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteDomainDataSmdSmdIDOK creates a DeleteDomainDataSmdSmdIDOK with default headers values
func NewDeleteDomainDataSmdSmdIDOK() *DeleteDomainDataSmdSmdIDOK {
	return &DeleteDomainDataSmdSmdIDOK{}
}

/*DeleteDomainDataSmdSmdIDOK handles this case with default header values.

return 'void'
*/
type DeleteDomainDataSmdSmdIDOK struct {
}

func (o *DeleteDomainDataSmdSmdIDOK) Error() string {
	return fmt.Sprintf("[DELETE /domain/data/smd/{smdId}][%d] deleteDomainDataSmdSmdIdOK ", 200)
}

func (o *DeleteDomainDataSmdSmdIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteDomainDataSmdSmdIDDefault creates a DeleteDomainDataSmdSmdIDDefault with default headers values
func NewDeleteDomainDataSmdSmdIDDefault(code int) *DeleteDomainDataSmdSmdIDDefault {
	return &DeleteDomainDataSmdSmdIDDefault{
		_statusCode: code,
	}
}

/*DeleteDomainDataSmdSmdIDDefault handles this case with default header values.

Unexpected error
*/
type DeleteDomainDataSmdSmdIDDefault struct {
	_statusCode int

	Payload *models.DeleteDomainDataSmdSmdIDDefaultBody
}

// Code gets the status code for the delete domain data smd smd ID default response
func (o *DeleteDomainDataSmdSmdIDDefault) Code() int {
	return o._statusCode
}

func (o *DeleteDomainDataSmdSmdIDDefault) Error() string {
	return fmt.Sprintf("[DELETE /domain/data/smd/{smdId}][%d] DeleteDomainDataSmdSmdID default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteDomainDataSmdSmdIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeleteDomainDataSmdSmdIDDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
