// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017 The go-ovh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetDomainZoneZoneNameStatusParams creates a new GetDomainZoneZoneNameStatusParams object
// with the default values initialized.
func NewGetDomainZoneZoneNameStatusParams() *GetDomainZoneZoneNameStatusParams {
	var ()
	return &GetDomainZoneZoneNameStatusParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDomainZoneZoneNameStatusParamsWithTimeout creates a new GetDomainZoneZoneNameStatusParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDomainZoneZoneNameStatusParamsWithTimeout(timeout time.Duration) *GetDomainZoneZoneNameStatusParams {
	var ()
	return &GetDomainZoneZoneNameStatusParams{

		timeout: timeout,
	}
}

// NewGetDomainZoneZoneNameStatusParamsWithContext creates a new GetDomainZoneZoneNameStatusParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDomainZoneZoneNameStatusParamsWithContext(ctx context.Context) *GetDomainZoneZoneNameStatusParams {
	var ()
	return &GetDomainZoneZoneNameStatusParams{

		Context: ctx,
	}
}

// NewGetDomainZoneZoneNameStatusParamsWithHTTPClient creates a new GetDomainZoneZoneNameStatusParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDomainZoneZoneNameStatusParamsWithHTTPClient(client *http.Client) *GetDomainZoneZoneNameStatusParams {
	var ()
	return &GetDomainZoneZoneNameStatusParams{
		HTTPClient: client,
	}
}

/*GetDomainZoneZoneNameStatusParams contains all the parameters to send to the API endpoint
for the get domain zone zone name status operation typically these are written to a http.Request
*/
type GetDomainZoneZoneNameStatusParams struct {

	/*ZoneName*/
	ZoneName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get domain zone zone name status params
func (o *GetDomainZoneZoneNameStatusParams) WithTimeout(timeout time.Duration) *GetDomainZoneZoneNameStatusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get domain zone zone name status params
func (o *GetDomainZoneZoneNameStatusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get domain zone zone name status params
func (o *GetDomainZoneZoneNameStatusParams) WithContext(ctx context.Context) *GetDomainZoneZoneNameStatusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get domain zone zone name status params
func (o *GetDomainZoneZoneNameStatusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get domain zone zone name status params
func (o *GetDomainZoneZoneNameStatusParams) WithHTTPClient(client *http.Client) *GetDomainZoneZoneNameStatusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get domain zone zone name status params
func (o *GetDomainZoneZoneNameStatusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithZoneName adds the zoneName to the get domain zone zone name status params
func (o *GetDomainZoneZoneNameStatusParams) WithZoneName(zoneName string) *GetDomainZoneZoneNameStatusParams {
	o.SetZoneName(zoneName)
	return o
}

// SetZoneName adds the zoneName to the get domain zone zone name status params
func (o *GetDomainZoneZoneNameStatusParams) SetZoneName(zoneName string) {
	o.ZoneName = zoneName
}

// WriteToRequest writes these params to a swagger request
func (o *GetDomainZoneZoneNameStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param zoneName
	if err := r.SetPathParam("zoneName", o.ZoneName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
