// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017 The go-ovh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/appscode/go-ovh/domain/models"
)

// PostDomainServiceNameOwoReader is a Reader for the PostDomainServiceNameOwo structure.
type PostDomainServiceNameOwoReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostDomainServiceNameOwoReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostDomainServiceNameOwoOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewPostDomainServiceNameOwoDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostDomainServiceNameOwoOK creates a PostDomainServiceNameOwoOK with default headers values
func NewPostDomainServiceNameOwoOK() *PostDomainServiceNameOwoOK {
	return &PostDomainServiceNameOwoOK{}
}

/*PostDomainServiceNameOwoOK handles this case with default header values.

return value
*/
type PostDomainServiceNameOwoOK struct {
	Payload []string
}

func (o *PostDomainServiceNameOwoOK) Error() string {
	return fmt.Sprintf("[POST /domain/{serviceName}/owo][%d] postDomainServiceNameOwoOK  %+v", 200, o.Payload)
}

func (o *PostDomainServiceNameOwoOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostDomainServiceNameOwoDefault creates a PostDomainServiceNameOwoDefault with default headers values
func NewPostDomainServiceNameOwoDefault(code int) *PostDomainServiceNameOwoDefault {
	return &PostDomainServiceNameOwoDefault{
		_statusCode: code,
	}
}

/*PostDomainServiceNameOwoDefault handles this case with default header values.

Unexpected error
*/
type PostDomainServiceNameOwoDefault struct {
	_statusCode int

	Payload *models.PostDomainServiceNameOwoDefaultBody
}

// Code gets the status code for the post domain service name owo default response
func (o *PostDomainServiceNameOwoDefault) Code() int {
	return o._statusCode
}

func (o *PostDomainServiceNameOwoDefault) Error() string {
	return fmt.Sprintf("[POST /domain/{serviceName}/owo][%d] PostDomainServiceNameOwo default  %+v", o._statusCode, o.Payload)
}

func (o *PostDomainServiceNameOwoDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PostDomainServiceNameOwoDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
