// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017 The go-ovh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/appscode/go-ovh/domain/models"
)

// PostDomainDataSmdReader is a Reader for the PostDomainDataSmd structure.
type PostDomainDataSmdReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostDomainDataSmdReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostDomainDataSmdOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewPostDomainDataSmdDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostDomainDataSmdOK creates a PostDomainDataSmdOK with default headers values
func NewPostDomainDataSmdOK() *PostDomainDataSmdOK {
	return &PostDomainDataSmdOK{}
}

/*PostDomainDataSmdOK handles this case with default header values.

description of 'domain.Data.Smd' response
*/
type PostDomainDataSmdOK struct {
	Payload *models.DomainDataSmd
}

func (o *PostDomainDataSmdOK) Error() string {
	return fmt.Sprintf("[POST /domain/data/smd][%d] postDomainDataSmdOK  %+v", 200, o.Payload)
}

func (o *PostDomainDataSmdOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DomainDataSmd)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostDomainDataSmdDefault creates a PostDomainDataSmdDefault with default headers values
func NewPostDomainDataSmdDefault(code int) *PostDomainDataSmdDefault {
	return &PostDomainDataSmdDefault{
		_statusCode: code,
	}
}

/*PostDomainDataSmdDefault handles this case with default header values.

Unexpected error
*/
type PostDomainDataSmdDefault struct {
	_statusCode int

	Payload *models.PostDomainDataSmdDefaultBody
}

// Code gets the status code for the post domain data smd default response
func (o *PostDomainDataSmdDefault) Code() int {
	return o._statusCode
}

func (o *PostDomainDataSmdDefault) Error() string {
	return fmt.Sprintf("[POST /domain/data/smd][%d] PostDomainDataSmd default  %+v", o._statusCode, o.Payload)
}

func (o *PostDomainDataSmdDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PostDomainDataSmdDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
