// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017 The go-ovh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CloudSubnetworkRegionIPPool IPPool
// swagger:model cloud.SubnetworkRegion.IPPool
type CloudSubnetworkRegionIPPool struct {

	// Last IP for this region (eg: 192.168.1.24)
	// Required: true
	// Read Only: true
	End string `json:"end"`

	// First IP for this region (eg: 192.168.1.12)
	// Required: true
	// Read Only: true
	Start string `json:"start"`
}

// Validate validates this cloud subnetwork region IP pool
func (m *CloudSubnetworkRegionIPPool) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEnd(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateStart(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CloudSubnetworkRegionIPPool) validateEnd(formats strfmt.Registry) error {

	if err := validate.RequiredString("end", "body", string(m.End)); err != nil {
		return err
	}

	return nil
}

func (m *CloudSubnetworkRegionIPPool) validateStart(formats strfmt.Registry) error {

	if err := validate.RequiredString("start", "body", string(m.Start)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CloudSubnetworkRegionIPPool) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CloudSubnetworkRegionIPPool) UnmarshalBinary(b []byte) error {
	var res CloudSubnetworkRegionIPPool
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
