// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017 The go-ovh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CloudQuotaVolumeQuotas VolumeQuotas
// swagger:model cloud.Quota.VolumeQuotas
type CloudQuotaVolumeQuotas struct {

	// Maximum total volume capacity allowed in your project
	// Required: true
	// Read Only: true
	MaxGigabytes int64 `json:"maxGigabytes"`

	// Current used volume gigabytes
	// Required: true
	// Read Only: true
	UsedGigabytes int64 `json:"usedGigabytes"`

	// Current volumes count
	// Required: true
	// Read Only: true
	VolumeCount int64 `json:"volumeCount"`
}

// Validate validates this cloud quota volume quotas
func (m *CloudQuotaVolumeQuotas) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMaxGigabytes(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateUsedGigabytes(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateVolumeCount(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CloudQuotaVolumeQuotas) validateMaxGigabytes(formats strfmt.Registry) error {

	if err := validate.Required("maxGigabytes", "body", int64(m.MaxGigabytes)); err != nil {
		return err
	}

	return nil
}

func (m *CloudQuotaVolumeQuotas) validateUsedGigabytes(formats strfmt.Registry) error {

	if err := validate.Required("usedGigabytes", "body", int64(m.UsedGigabytes)); err != nil {
		return err
	}

	return nil
}

func (m *CloudQuotaVolumeQuotas) validateVolumeCount(formats strfmt.Registry) error {

	if err := validate.Required("volumeCount", "body", int64(m.VolumeCount)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CloudQuotaVolumeQuotas) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CloudQuotaVolumeQuotas) UnmarshalBinary(b []byte) error {
	var res CloudQuotaVolumeQuotas
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
