// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017 The go-ovh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/appscode/go-ovh/vip/models"
)

// GetVipServiceNameServiceInfosReader is a Reader for the GetVipServiceNameServiceInfos structure.
type GetVipServiceNameServiceInfosReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetVipServiceNameServiceInfosReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetVipServiceNameServiceInfosOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetVipServiceNameServiceInfosDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetVipServiceNameServiceInfosOK creates a GetVipServiceNameServiceInfosOK with default headers values
func NewGetVipServiceNameServiceInfosOK() *GetVipServiceNameServiceInfosOK {
	return &GetVipServiceNameServiceInfosOK{}
}

/*GetVipServiceNameServiceInfosOK handles this case with default header values.

description of 'services.Service' response
*/
type GetVipServiceNameServiceInfosOK struct {
	Payload *models.ServicesService
}

func (o *GetVipServiceNameServiceInfosOK) Error() string {
	return fmt.Sprintf("[GET /vip/{serviceName}/serviceInfos][%d] getVipServiceNameServiceInfosOK  %+v", 200, o.Payload)
}

func (o *GetVipServiceNameServiceInfosOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServicesService)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetVipServiceNameServiceInfosDefault creates a GetVipServiceNameServiceInfosDefault with default headers values
func NewGetVipServiceNameServiceInfosDefault(code int) *GetVipServiceNameServiceInfosDefault {
	return &GetVipServiceNameServiceInfosDefault{
		_statusCode: code,
	}
}

/*GetVipServiceNameServiceInfosDefault handles this case with default header values.

Unexpected error
*/
type GetVipServiceNameServiceInfosDefault struct {
	_statusCode int

	Payload *models.GetVipServiceNameServiceInfosDefaultBody
}

// Code gets the status code for the get vip service name service infos default response
func (o *GetVipServiceNameServiceInfosDefault) Code() int {
	return o._statusCode
}

func (o *GetVipServiceNameServiceInfosDefault) Error() string {
	return fmt.Sprintf("[GET /vip/{serviceName}/serviceInfos][%d] GetVipServiceNameServiceInfos default  %+v", o._statusCode, o.Payload)
}

func (o *GetVipServiceNameServiceInfosDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetVipServiceNameServiceInfosDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
